project:
  type: default
  output-dir: _output
  render:
    - quarto/Asset_Transfer_Case_Research_Workplan.qmd
    - quarto/Asset_Transfer_Cases_Initial_Research.qmd
    - quarto/Asset_Transfer_Cases_Initial_Research_UKR.qmd
    - quarto/German_Sanction_Mechanism_Analysis.qmd
    - quarto/German_Sanctions_3Page_Summary.qmd
    - quarto/German_Sanction_Mechanism_Analysis_UKR.qmd
    - quarto/German_Sanctions_3Page_Summary_UKR.qmd
    - quarto/German_Sanctions_Criminal_Asset_Pipeline_3Page.qmd
    - quarto/German_Sanctions_Criminal_Asset_Pipeline_3Page_UKR.qmd

format:
  pdf:
    fig-width: 6
    fig-align: center
  html:
    fig-width: 6
    fig-align: center
    mermaid:
      theme: neutral
