<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Artem Radin">
<meta name="dcterms.date" content="2026-03-04">

<title>Asset Transfer Cases: Initial Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Asset_Transfer_Cases_Initial_Research_files/libs/clipboard/clipboard.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/popper.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/anchor.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-66f220744880a257c6c06aa45740e4a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="mermaid-theme" content="neutral">
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="styles/summary.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose"><span class="header-section-number">1</span> Purpose</a></li>
  <li><a href="#preliminary-finding" id="toc-preliminary-finding" class="nav-link" data-scroll-target="#preliminary-finding"><span class="header-section-number">2</span> Preliminary Finding</a></li>
  <li><a href="#initial-case-table-expanded" id="toc-initial-case-table-expanded" class="nav-link" data-scroll-target="#initial-case-table-expanded"><span class="header-section-number">3</span> Initial Case Table (Expanded)</a></li>
  <li><a href="#court-decision-links-and-transfer-nexus-priority-cases" id="toc-court-decision-links-and-transfer-nexus-priority-cases" class="nav-link" data-scroll-target="#court-decision-links-and-transfer-nexus-priority-cases"><span class="header-section-number">4</span> Court Decision Links and Transfer Nexus (Priority Cases)</a></li>
  <li><a href="#case-template-completion-current-status" id="toc-case-template-completion-current-status" class="nav-link" data-scroll-target="#case-template-completion-current-status"><span class="header-section-number">5</span> Case Template Completion (Current Status)</a></li>
  <li><a href="#domestic-transfer-cases" id="toc-domestic-transfer-cases" class="nav-link" data-scroll-target="#domestic-transfer-cases"><span class="header-section-number">6</span> Domestic Transfer Cases</a></li>
  <li><a href="#cross-border-transfer-cases" id="toc-cross-border-transfer-cases" class="nav-link" data-scroll-target="#cross-border-transfer-cases"><span class="header-section-number">7</span> Cross-Border Transfer Cases</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Asset_Transfer_Cases_Initial_Research.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Asset Transfer Cases: Initial Research</h1>
<p class="subtitle lead">Verified Domestic and Cross-Border Transfers of Confiscated Criminal Assets</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Artem Radin </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Intern
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="purpose"><span class="header-section-number">1</span> Purpose</h2>
<p>This note is an <strong>initial case-based research draft</strong> responding to the request to focus on <strong>actual transfers of confiscated criminal assets</strong>, not just on abstract legal pathways. It identifies verified examples of:</p>
<ul>
<li><strong>domestic transfers</strong> from forfeited assets to victims; and</li>
<li><strong>cross-border transfers</strong> from one state to another or to a monitored public-benefit mechanism.</li>
</ul>
<p>The note relies primarily on <strong>official sources</strong>. Court decisions and formal instruments are included where they were readily identifiable from official materials.</p>
</section>
<section id="preliminary-finding" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="preliminary-finding"><span class="header-section-number">2</span> Preliminary Finding</h2>
<p>The first review suggests a clear pattern. In the strongest public examples, asset transfer usually requires <strong>three distinct steps</strong>:</p>
<ol type="1">
<li><strong>Final confiscation / forfeiture / settlement</strong> in the recovering state.</li>
<li><strong>A legal allocation mechanism</strong> for victims or a foreign beneficiary.</li>
<li><strong>A monitored implementation vehicle</strong>, especially in cross-border corruption cases.</li>
</ol>
<p>This is why the most developed models are not simple “state A seizes, then wires money to state B” cases. They usually combine confiscation with a remission process, a restitution agreement, or a monitored trust-fund or project structure.</p>
</section>
<section id="initial-case-table-expanded" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="initial-case-table-expanded"><span class="header-section-number">3</span> Initial Case Table (Expanded)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Case</th>
<th>Jurisdiction(s)</th>
<th>Transfer type</th>
<th>Amount transferred</th>
<th>Recipient</th>
<th>Main legal mechanism</th>
<th>Court decision / legal instrument link</th>
<th>Verification status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Switzerland -&gt; Nigeria (Abacha II)</td>
<td>Switzerland / Nigeria</td>
<td>Cross-border</td>
<td>USD 321 million</td>
<td>Nigerian population via social protection project</td>
<td>Confiscation in Swiss proceedings + tripartite agreement with World Bank monitoring</td>
<td>Swiss Federal Supreme Court (Abacha mutual legal assistance/confiscation framework) 1A.215/2004 (ATF 131 II 169)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> + 2017 tripartite agreement<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></td>
<td>Verified (official sources + court decision)</td>
</tr>
<tr class="even">
<td>UK -&gt; Nigeria (Ibori)</td>
<td>UK / Nigeria</td>
<td>Cross-border</td>
<td>GBP 4.2 million</td>
<td>Nigerian infrastructure projects</td>
<td>UK recovery proceedings + UK-Nigeria return agreement</td>
<td>UK-Nigeria MoU annex confirming confiscation orders since 2010<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></td>
<td>Verified (official source). Court-order text not yet located in public full text</td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Malaysia (1MDB)</td>
<td>U.S. / Malaysia</td>
<td>Cross-border</td>
<td>about USD 1.4 billion</td>
<td>people of Malaysia</td>
<td>U.S. forfeiture litigation + DOJ repatriation</td>
<td>U.S. Court of Appeals (9th Cir.) in related 1MDB-linked forfeiture action, <em>U.S. v. PetroSaudi Oil Services</em> (13 Jun 2023)<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> + DOJ repatriation release<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></td>
<td>Verified (official source + court decision)</td>
</tr>
</tbody>
</table>
</section>
<section id="court-decision-links-and-transfer-nexus-priority-cases" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="court-decision-links-and-transfer-nexus-priority-cases"><span class="header-section-number">4</span> Court Decision Links and Transfer Nexus (Priority Cases)</h2>
<section id="switzerland---nigeria-abacha" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="switzerland---nigeria-abacha"><span class="header-section-number">4.1</span> Switzerland -&gt; Nigeria (Abacha)</h3>
<p>Switzerland returned <strong>USD 321 million</strong> of Abacha-linked assets to Nigeria under a tripartite agreement with World Bank monitoring.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Nigeria requested MLA; Swiss courts confirmed cooperation parameters (ATF 131 II 169, 2005);<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> Geneva prosecutor confiscated assets (2016);<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> funds were disbursed tranche-based to the National Social Safety Net Project for cash transfers to poor households.</p>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        A1["Step 1: Nigeria submits MLA request to Switzerland&lt;br/&gt;for Abacha-linked assets held in Swiss banks"]
        A2["Step 2: Swiss authorities conduct IRSG admissibility review&lt;br/&gt;assess cooperation conditions under mutual legal assistance"]
        A3["Step 3: Swiss Federal Supreme Court ATF 131 II 169&lt;br/&gt;7 Feb 2005 — confirms legal parameters for cooperation and return"]
        A4["Step 4: Geneva prosecutor initiates criminal proceedings&lt;br/&gt;against Abba Abacha and related parties"]
        A5["Step 5: Swiss court Dec 2014: repatriation conditional on&lt;br/&gt;World Bank monitoring of use of funds"]
        A6["Step 6: Geneva Attorney General confiscates assets&lt;br/&gt;8 Mar 2016 — return process becomes legally possible"]
        A7["Step 7: Nigeria designates use: National Social Safety Net Project&lt;br/&gt;targeted cash transfers to poor and vulnerable Nigerians"]
        A8["Step 8: 4 Dec 2017: Tripartite MOU signed&lt;br/&gt;Switzerland, Nigeria, World Bank — USD 321 million"]
        A9["Step 9: Tranche-based disbursement to Nigeria&lt;br/&gt;funds applied to National Social Safety Net Project"]
        A10["Step 10: Cash transfers to beneficiaries&lt;br/&gt;poor and vulnerable Nigerians via IDA-financed project"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        M1["World Bank: monitors use of funds&lt;br/&gt;same manner as IDA Credit for National Social Safety Net Project"]
        M2["Nigerian CSOs under Network on Asset Recovery&lt;br/&gt;expertise in anti-corruption and asset recovery"]
        M3["CSOs monitor cash-to-beneficiaries&lt;br/&gt;bi-annual reports on use of funds"]
        M4["Transparency and accountability framework&lt;br/&gt;civil society oversight per tripartite agreement"]
    end

    A1 --&gt; A2 --&gt; A3 --&gt; A4 --&gt; A5 --&gt; A6 --&gt; A7 --&gt; A8 --&gt; A9 --&gt; A10
    A8 -.-&gt;|"enables"| M1
    A9 -.-&gt;|"subject to"| M2
    M2 --&gt; M3
    M1 --&gt; M4
    M3 --&gt; M4

    A1 -.-&gt; NA1
    A2 -.-&gt; NA2
    A3 -.-&gt; NA3
    A4 -.-&gt; NA4
    A5 -.-&gt; NA5
    A6 -.-&gt; NA6
    A7 -.-&gt; NA7
    A8 -.-&gt; NA8
    A9 -.-&gt; NA9
    A10 -.-&gt; NA10

    NA1["MLA request under Swiss IRSG Bundesgesetz über internationale Rechtshilfe in Strafsachen; assets traced to late Gen. Sani Abacha and family in Swiss banks; Nigeria as requesting state."]
    NA2["OFJ and cantonal authorities assessed admissibility under IRSG Art. 3; dual criminality and cooperation conditions reviewed."]
    NA3["ATF 131 II 169 7 Feb 2005 case 1A.215/2004; confirmed MLA and return parameters under IRSG while proceedings ongoing in Nigeria."]
    NA4["Procureur général de Genève initiated criminal proceedings against Abba Abacha; assets identified, frozen under Swiss criminal procedure."]
    NA5["Dec 2014 Swiss court ruling: repatriation conditional on World Bank monitoring of use; precondition for transfer."]
    NA6["8 Mar 2016 Procureur général Genève confiscation order; assets transferred to Swiss Confederation under Art. 69-72 SCC."]
    NA7["Nigeria designated National Social Safety Net Project P151488; IDA Credit; targeted cash transfers to poor households."]
    NA8["4 Dec 2017 tripartite MOU: Federal Govt Nigeria, Swiss Federal Council, World Bank; disbursement modalities and WB monitoring role."]
    NA9["Tranche-based release; funds applied to IDA-financed National Social Safety Net Project; same monitoring as IDA Credit."]
    NA10["Cash to beneficiaries; NAR CSOs monitor cash-to-beneficiaries; bi-annual reports per tripartite agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NA1,NA2,NA3,NA4,NA5,NA6,NA7,NA8,NA9,NA10 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="u.s.---malaysia-1mdb" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="u.s.---malaysia-1mdb"><span class="header-section-number">4.2</span> U.S. -&gt; Malaysia (1MDB)</h3>
<p>The U.S. repatriated <strong>~USD 1.4 billion</strong> of 1MDB proceeds to Malaysia via civil forfeiture (41 actions from 2016) and DOJ repatriation tranches.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Assets were transferred to the Malaysia 1MDB Asset Recovery Trust Account for public benefit. The Ninth Circuit affirmed seizure authority in a related PetroSaudi forfeiture action (2023).<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        B1["Step 1: DOJ initiates civil forfeiture actions&lt;br/&gt;from Jul 2016 — 41 actions targeting 1MDB-linked assets"]
        B2["Step 2: U.S. district courts order restraint and seizure&lt;br/&gt;preservation of res during litigation"]
        B3["Step 3: Ninth Circuit affirms seizure-preservation orders&lt;br/&gt;13 Jun 2023 — PetroSaudi-related track upheld"]
        B4["Step 4: Forfeiture pipeline: settlements and dispositions&lt;br/&gt;assets converted to recoverable value under U.S. law"]
        B5["Step 5: DOJ repatriation tranche decisions&lt;br/&gt;executive/legal-policy determination for Malaysia"]
        B6["Step 6: Transfer to Malaysia 1MDB Asset Recovery Trust Account&lt;br/&gt;e.g. USD 452m Aug 2021, USD 156m Jun 2024 — total ~USD 1.4bn"]
        B7["Step 7: Funds for benefit of people of Malaysia&lt;br/&gt;administered via Malaysian trust vehicle"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        N1["Malaysian 1MDB Asset Recovery Trust Account&lt;br/&gt;designated vehicle for repatriated proceeds"]
        N2["Trust account administration&lt;br/&gt;use for public benefit per agreement"]
        N3["Bilateral U.S.–Malaysia repatriation framework&lt;br/&gt;tranche-based returns with designated destination"]
    end

    B1 --&gt; B2 --&gt; B3 --&gt; B4 --&gt; B5 --&gt; B6 --&gt; B7
    B5 -.-&gt;|"governs"| N1
    B6 -.-&gt;|"to"| N1
    N1 --&gt; N2
    N2 --&gt; N3

    B1 -.-&gt; NB1
    B2 -.-&gt; NB2
    B3 -.-&gt; NB3
    B4 -.-&gt; NB4
    B5 -.-&gt; NB5
    B6 -.-&gt; NB6
    B7 -.-&gt; NB7

    NB1["41 in rem civil forfeiture actions under 18 USC 981 from Jul 2016; Kleptocracy Asset Recovery Initiative; assets traceable to 1MDB."]
    NB2["District court restraining orders and warrants of arrest in rem; 18 USC 981; res preserved pending forfeiture litigation."]
    NB3["9th Cir. U.S. v. PetroSaudi Oil Services Nos. 21-56228 22-55025 13 Jun 2023; affirmed interlocutory orders; USD 380m arbitration fund."]
    NB4["Settlements and default judgments under 18 USC 981; assets converted to recoverable value; DOJ disposition authority."]
    NB5["DOJ MLARS repatriation decision; assets legally forfeited; tranche determination under bilateral U.S.-Malaysia framework."]
    NB6["Wire to 1MDB Asset Recovery Trust Account; USD 452m Aug 2021, USD 156m Jun 2024; total ~USD 1.4bn per DOJ."]
    NB7["Trust account administered for benefit of people of Malaysia; designated recipient per bilateral repatriation agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NB1,NB2,NB3,NB4,NB5,NB6,NB7 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="uk---nigeria-ibori" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="uk---nigeria-ibori"><span class="header-section-number">4.3</span> UK -&gt; Nigeria (Ibori)</h3>
<p>The UK returned <strong>GBP 4.2 million</strong> to Nigeria from proceeds recovered under confiscation orders since 2010.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> The 2021 UK-Nigeria agreement earmarked funds for infrastructure (Lagos-Ibadan Expressway, Abuja-Kano road, second Niger Bridge).<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> Cleen Foundation provides independent monitoring; Nigeria Sovereign Investment Authority administers implementation. Full-text public copy of the underlying confiscation orders is pending.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        C1["Step 1: UK investigation: Met Police, NCA, CPS&lt;br/&gt;Ibori network — money laundering, fraud, forgery"]
        C2["Step 2: Feb 2012: Ibori pleads guilty in UK court&lt;br/&gt;13 years imprisonment"]
        C3["Step 3: UK confiscation orders since 2010&lt;br/&gt;recoverable criminal property value established"]
        C4["Step 4: UK–Nigeria return negotiations&lt;br/&gt;framework for destination and safeguards"]
        C5["Step 5: 9 Mar 2021: UK–Nigeria agreement and annex signed&lt;br/&gt;GBP 4.2 million — project use and oversight conditions"]
        C6["Step 6: Transfer of GBP 4.2m to Nigeria&lt;br/&gt;under bilateral MoU"]
        C7["Step 7: Projects: Lagos–Ibadan Expressway, Abuja–Kano road&lt;br/&gt;second Niger Bridge — infrastructure and public benefit"]
        C8["Step 8: Nigeria Sovereign Investment Authority&lt;br/&gt;administers project implementation"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        O1["Cleen Foundation: independent monitoring&lt;br/&gt;expertise in infrastructure, anti-corruption, procurement"]
        O2["Federal Republic of Nigeria Monitoring Team&lt;br/&gt;oversees implementation, regular progress reporting"]
        O3["Budget plan and work/expenditure schedule&lt;br/&gt;per project, agreed by UK and Nigerian representatives"]
        O4["Annual accountability reports&lt;br/&gt;published, information to Nigerian public"]
        O5["Bar on disbursement to perpetrators&lt;br/&gt;and related persons per annex"]
    end

    C1 --&gt; C2 --&gt; C3 --&gt; C4 --&gt; C5 --&gt; C6 --&gt; C7 --&gt; C8
    C5 -.-&gt;|"requires"| O1
    C6 -.-&gt;|"subject to"| O2
    O1 --&gt; O3
    O2 --&gt; O4
    O3 --&gt; O5
    O4 --&gt; O5

    C1 -.-&gt; NC1
    C2 -.-&gt; NC2
    C3 -.-&gt; NC3
    C4 -.-&gt; NC4
    C5 -.-&gt; NC5
    C6 -.-&gt; NC6
    C7 -.-&gt; NC7
    C8 -.-&gt; NC8

    NC1["Met Police Proceeds of Crime Unit, NCA, CPS; POCA 2002; money laundering s.327, conspiracy to defraud, forgery; Ibori network."]
    NC2["Southwark Crown Court Feb 2012; Ibori guilty plea; 13 years; confiscation proceedings under POCA s.6 followed."]
    NC3["Confiscation orders under POCA s.6 since 2010; recoverable amount and criminal property value; annex confirms order basis."]
    NC4["UK-Nigeria negotiations under 2016 MoU; return framework; destination, project earmarking, audit safeguards."]
    NC5["9 Mar 2021 UK-Nigeria agreement and annex; GBP 4.2m; budget plan and work schedule per project; bar on perpetrator disbursement."]
    NC6["Transfer under bilateral MoU; first return under 2016 framework; funds to NSIA for designated projects."]
    NC7["Earmarked: Lagos-Ibadan Expressway, Abuja-Kano road, second Niger Bridge; infrastructure and public benefit."]
    NC8["NSIA administers; Cleen Foundation independent monitoring; Federal Monitoring Team; annual accountability reports to public."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NC1,NC2,NC3,NC4,NC5,NC6,NC7,NC8 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="case-template-completion-current-status" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="case-template-completion-current-status"><span class="header-section-number">5</span> Case Template Completion (Current Status)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Case</th>
<th>Crime type</th>
<th>Authority</th>
<th>Legal basis / instrument</th>
<th>Court decision link</th>
<th>Verification status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>U.S. -&gt; Madoff victims</td>
<td>Fraud / Ponzi scheme / money laundering proceeds</td>
<td>U.S. DOJ (MLARS) and appointed fund administration</td>
<td>U.S. forfeiture + DOJ victim fund distribution process</td>
<td>Not prioritized for this tranche</td>
<td>Verified</td>
</tr>
<tr class="even">
<td>U.S. -&gt; Western Union victims</td>
<td>Fraud facilitation and AML failures linked to consumer scams</td>
<td>U.S. DOJ</td>
<td>Forfeiture + remission process under DOJ administration</td>
<td>Not prioritized for this tranche</td>
<td>Verified</td>
</tr>
<tr class="odd">
<td>Switzerland -&gt; Nigeria (Abacha II)</td>
<td>Corruption / embezzlement / laundering of illicit state assets</td>
<td>Swiss prosecutorial and federal authorities; FDFA; World Bank (monitoring role)</td>
<td>Swiss confiscation framework + tripartite restitution agreement (2017)</td>
<td>ATF 131 II 169 (1A.215/2004)<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></td>
<td>Verified (strong)</td>
</tr>
<tr class="even">
<td>UK -&gt; Nigeria (Ibori)</td>
<td>Corruption and laundering-related proceeds linked to Ibori network</td>
<td>UK government authorities; Nigerian authorities</td>
<td>Confiscation orders (since 2010) + UK-Nigeria return annex (2021)</td>
<td>Annex confirms confiscation-order basis; full court order text pending</td>
<td>Verified with court-text gap</td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Malaysia (1MDB)</td>
<td>Large-scale misappropriation / bribery / money laundering</td>
<td>U.S. DOJ; U.S. federal courts</td>
<td>Civil forfeiture actions + DOJ repatriation decisions</td>
<td>Ninth Circuit decision in related forfeiture action<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></td>
<td>Verified (strong)</td>
</tr>
</tbody>
</table>
</section>
<section id="domestic-transfer-cases" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="domestic-transfer-cases"><span class="header-section-number">6</span> Domestic Transfer Cases</h2>
<section id="u.s.-madoff-victim-fund" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="u.s.-madoff-victim-fund"><span class="header-section-number">6.1</span> 1. U.S. Madoff Victim Fund</h3>
<p>This is one of the clearest public examples of <strong>forfeited assets being redistributed to victims at scale</strong>. On 30 December 2024, the U.S. Department of Justice announced the <strong>10th and final distribution</strong> of the Madoff Victim Fund. The Department stated that more than <strong>USD 4.3 billion</strong> in forfeited funds had been paid to <strong>40,930 victims in 127 countries</strong>, bringing aggregate recovery to <strong>93.71% of fraud losses</strong>.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p>The legal step preceding the transfer was the U.S. government’s recovery of assets through <strong>civil and criminal forfeiture connected to the Bernard L. Madoff fraud scheme</strong>. The transfer mechanism was not an ad hoc political decision, but a formal DOJ-administered victim compensation structure.</p>
<p>Why it matters: this is a strong example of a <strong>domestic victim-compensation model</strong> built on forfeited assets rather than on ordinary restitution alone.</p>
</section>
<section id="u.s.-western-union-remission-fund" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="u.s.-western-union-remission-fund"><span class="header-section-number">6.2</span> 2. U.S. Western Union Remission Fund</h3>
<p>Western Union is another strong domestic model because the DOJ publicly explains both the <strong>forfeiture event</strong> and the <strong>distribution process</strong>. On 9 September 2024, DOJ announced that the Western Union Remission Fund had begun its second distribution in phase two, transferring approximately <strong>USD 18.5 million</strong> to around <strong>3,000 victims</strong>. DOJ stated that, across both phases, the fund had already distributed <strong>over USD 420 million</strong> to <strong>more than 175,000 victims</strong>, who received full compensation for their losses.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
<p>The official materials connect the transfer to <strong>funds forfeited to the United States from Western Union</strong>. The compensation mechanism was <strong>remission</strong>, a formal administrative process through which forfeited funds can be returned to victims.</p>
<p>Why it matters: this case shows that a transfer to victims can be structured even when the proceeds first pass through the state, provided there is a clear remission framework and a verified class of victims.</p>
</section>
</section>
<section id="cross-border-transfer-cases" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="cross-border-transfer-cases"><span class="header-section-number">7</span> Cross-Border Transfer Cases</h2>
<section id="switzerland---nigeria-abacha-ii" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="switzerland---nigeria-abacha-ii"><span class="header-section-number">7.1</span> 3. Switzerland -&gt; Nigeria (Abacha II)</h3>
<p>Switzerland’s return of Abacha assets is one of the best documented cross-border models. According to the Swiss Federal Department of Foreign Affairs, on <strong>4 December 2017</strong> Switzerland, Nigeria and the World Bank signed a <strong>tripartite agreement</strong> governing the restitution of approximately <strong>USD 321 million</strong> to Nigeria’s population.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
<p>The official Swiss explanation is important because it identifies the legal step that came before transfer: the funds had been <strong>repatriated and confiscated by Switzerland as part of criminal proceedings brought by the public prosecutor’s office of Geneva against Abba Abacha</strong>.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a> A prior Swiss press release from <strong>8 March 2016</strong> states that the return process became possible after the <strong>Attorney General of the Canton of Geneva confiscated</strong> the assets.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></p>
<p>The agreement did not authorize an unrestricted transfer to the Nigerian state budget. Instead, it required <strong>World Bank-supported monitoring</strong>, tranche-based disbursement, and anti-misuse safeguards. The World Bank’s own factsheet likewise describes the arrangement as a monitored repatriation process.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></p>
<p>Why it matters: this is a leading example of <strong>confiscation plus monitored interstate restitution</strong>, which is likely more relevant for Ukraine than an unconditioned bilateral transfer.</p>
</section>
<section id="uk---nigeria-ibori-1" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="uk---nigeria-ibori-1"><span class="header-section-number">7.2</span> 4. UK -&gt; Nigeria (Ibori)</h3>
<p>On <strong>9 March 2021</strong>, the UK and Nigeria agreed the return of <strong>GBP 4.2 million</strong> recovered from associates of former Delta State Governor James Ibori.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a> The official UK press release says the money would be used for Nigerian infrastructure and public-benefit projects, and that implementation would be subject to monitoring and audit.</p>
<p>The associated UK publication of the agreement’s annex is useful because it identifies the legal precursor to the transfer. It states that the returned funds were recovered in proceedings resulting in <strong>confiscation orders made since 2010</strong>.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a> It also restricts the use of the money to specified projects and bars disbursement to alleged perpetrators and related persons.</p>
<p>Why it matters: this is a concise example of <strong>confiscation orders plus a bilateral implementation agreement</strong>. The transfer did not follow automatically from confiscation; the bilateral arrangement operationalized the destination and controls.</p>
<p>Court-link status: this initial tranche confirms the confiscation-order basis from official UK materials, but a full-text public copy of the operative confiscation orders is still pending.</p>
</section>
<section id="u.s.---malaysia-1mdb-1" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="u.s.---malaysia-1mdb-1"><span class="header-section-number">7.3</span> 5. U.S. -&gt; Malaysia (1MDB)</h3>
<p>The U.S. Department of Justice provides unusually clear official reporting on the repatriation of 1MDB proceeds. On <strong>13 June 2024</strong>, DOJ announced an additional <strong>USD 156 million</strong> repatriation to Malaysia, bringing the total returned by DOJ to approximately <strong>USD 1.4 billion</strong>.<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></p>
<p>DOJ links these returns to the long-running U.S. forfeiture campaign involving 1MDB proceeds. The Department states that, since July 2016, it had filed <strong>41 civil forfeiture actions</strong> and seized more than <strong>USD 1.7 billion</strong> in assets allegedly traceable to the scheme.<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>
<p>A published judicial layer is available in a related forfeiture track: in <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em> (Ninth Circuit, 13 June 2023), the court affirmed interlocutory orders preserving and permitting seizure of assets allegedly connected to 1MDB proceeds.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a> This did not itself order repatriation to Malaysia, but it upheld legal control over assets in the forfeiture pipeline that is necessary before transfer decisions.</p>
<p>Why it matters: 1MDB shows that large cross-border returns are possible, but only after a lengthy forfeiture phase, substantial tracing work, and a dedicated repatriation decision by the recovering state.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>U.S. Department of Justice, “Justice Department’s 10th Distribution Brings Total Provided to Over $4.3B in Nearly Full Recovery to Over 40,000 Victims in Madoff Ponzi Scheme”, 30 Dec 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery" class="uri">https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>U.S. Department of Justice, “Justice Department Begins Second Distribution of Forfeited Funds to Compensate Victims of Fraud Scheme Facilitated by Western Union”, 9 Sep 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud</a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>