<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Artem Radin">
<meta name="dcterms.date" content="2026-03-04">

<title>Asset Transfer Cases: Initial Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Asset_Transfer_Cases_Initial_Research_files/libs/clipboard/clipboard.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/popper.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/anchor.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-66f220744880a257c6c06aa45740e4a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles/summary.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose"><span class="header-section-number">1</span> Purpose</a></li>
  <li><a href="#preliminary-finding" id="toc-preliminary-finding" class="nav-link" data-scroll-target="#preliminary-finding"><span class="header-section-number">2</span> Preliminary Finding</a></li>
  <li><a href="#initial-case-table-expanded" id="toc-initial-case-table-expanded" class="nav-link" data-scroll-target="#initial-case-table-expanded"><span class="header-section-number">3</span> Initial Case Table (Expanded)</a></li>
  <li><a href="#court-decision-links-and-transfer-nexus-priority-cases" id="toc-court-decision-links-and-transfer-nexus-priority-cases" class="nav-link" data-scroll-target="#court-decision-links-and-transfer-nexus-priority-cases"><span class="header-section-number">4</span> Court Decision Links and Transfer Nexus (Priority Cases)</a></li>
  <li><a href="#case-template-completion-current-status" id="toc-case-template-completion-current-status" class="nav-link" data-scroll-target="#case-template-completion-current-status"><span class="header-section-number">5</span> Case Template Completion (Current Status)</a></li>
  <li><a href="#domestic-transfer-cases" id="toc-domestic-transfer-cases" class="nav-link" data-scroll-target="#domestic-transfer-cases"><span class="header-section-number">6</span> Domestic Transfer Cases</a></li>
  <li><a href="#cross-border-transfer-cases" id="toc-cross-border-transfer-cases" class="nav-link" data-scroll-target="#cross-border-transfer-cases"><span class="header-section-number">7</span> Cross-Border Transfer Cases</a></li>
  <li><a href="#switzerland-as-a-leading-model" id="toc-switzerland-as-a-leading-model" class="nav-link" data-scroll-target="#switzerland-as-a-leading-model"><span class="header-section-number">8</span> Switzerland as a Leading Model</a></li>
  <li><a href="#preliminary-implications-for-ukraine" id="toc-preliminary-implications-for-ukraine" class="nav-link" data-scroll-target="#preliminary-implications-for-ukraine"><span class="header-section-number">9</span> Preliminary Implications for Ukraine</a></li>
  <li><a href="#scope-confirmation-needed-from-management" id="toc-scope-confirmation-needed-from-management" class="nav-link" data-scroll-target="#scope-confirmation-needed-from-management"><span class="header-section-number">10</span> Scope Confirmation Needed From Management</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">11</span> Conclusion</a></li>
  <li><a href="#official-sources-used" id="toc-official-sources-used" class="nav-link" data-scroll-target="#official-sources-used"><span class="header-section-number">12</span> Official Sources Used</a></li>
  <li><a href="#link-spot-check-5-march-2026" id="toc-link-spot-check-5-march-2026" class="nav-link" data-scroll-target="#link-spot-check-5-march-2026"><span class="header-section-number">13</span> Link Spot-Check (5 March 2026)</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Asset_Transfer_Cases_Initial_Research.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Asset Transfer Cases: Initial Research</h1>
<p class="subtitle lead">Verified Domestic and Cross-Border Transfers of Confiscated Criminal Assets</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Artem Radin </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Intern
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="purpose"><span class="header-section-number">1</span> Purpose</h2>
<p>This note is an <strong>initial case-based research draft</strong> responding to the request to focus on <strong>actual transfers of confiscated criminal assets</strong>, not just on abstract legal pathways. It identifies verified examples of:</p>
<ul>
<li><strong>domestic transfers</strong> from forfeited assets to victims; and</li>
<li><strong>cross-border transfers</strong> from one state to another or to a monitored public-benefit mechanism.</li>
</ul>
<p>The note relies primarily on <strong>official sources</strong>. Court decisions and formal instruments are included where they were readily identifiable from official materials.</p>
</section>
<section id="preliminary-finding" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="preliminary-finding"><span class="header-section-number">2</span> Preliminary Finding</h2>
<p>The first review suggests a clear pattern. In the strongest public examples, asset transfer usually requires <strong>three distinct steps</strong>:</p>
<ol type="1">
<li><strong>Final confiscation / forfeiture / settlement</strong> in the recovering state.</li>
<li><strong>A legal allocation mechanism</strong> for victims or a foreign beneficiary.</li>
<li><strong>A monitored implementation vehicle</strong>, especially in cross-border corruption cases.</li>
</ol>
<p>This is why the most developed models are not simple “state A seizes, then wires money to state B” cases. They usually combine confiscation with a remission process, a restitution agreement, or a monitored trust-fund or project structure.</p>
</section>
<section id="initial-case-table-expanded" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="initial-case-table-expanded"><span class="header-section-number">3</span> Initial Case Table (Expanded)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Case</th>
<th>Jurisdiction(s)</th>
<th>Transfer type</th>
<th>Amount transferred</th>
<th>Recipient</th>
<th>Main legal mechanism</th>
<th>Court decision / legal instrument link</th>
<th>Verification status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>U.S. -&gt; Madoff victims</td>
<td>U.S.</td>
<td>Domestic</td>
<td>over USD 4.3 billion</td>
<td>40,930 victims in 127 countries</td>
<td>Forfeited funds distributed through DOJ-administered victim fund</td>
<td>DOJ victim fund release<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></td>
<td>Verified (official source)</td>
</tr>
<tr class="even">
<td>U.S. -&gt; Western Union fraud victims</td>
<td>U.S.</td>
<td>Domestic</td>
<td>over USD 420 million</td>
<td>more than 175,000 victims</td>
<td>Forfeited funds distributed through remission</td>
<td>DOJ remission release<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></td>
<td>Verified (official source)</td>
</tr>
<tr class="odd">
<td>Switzerland -&gt; Nigeria (Abacha II)</td>
<td>Switzerland / Nigeria</td>
<td>Cross-border</td>
<td>USD 321 million</td>
<td>Nigerian population via social protection project</td>
<td>Confiscation in Swiss proceedings + tripartite agreement with World Bank monitoring</td>
<td>Swiss Federal Supreme Court (Abacha mutual legal assistance/confiscation framework) 1A.215/2004 (ATF 131 II 169)<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> + 2017 tripartite agreement<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></td>
<td>Verified (official sources + court decision)</td>
</tr>
<tr class="even">
<td>UK -&gt; Nigeria (Ibori)</td>
<td>UK / Nigeria</td>
<td>Cross-border</td>
<td>GBP 4.2 million</td>
<td>Nigerian infrastructure projects</td>
<td>UK recovery proceedings + UK-Nigeria return agreement</td>
<td>UK-Nigeria MoU annex confirming confiscation orders since 2010<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></td>
<td>Verified (official source). Court-order text not yet located in public full text</td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Malaysia (1MDB)</td>
<td>U.S. / Malaysia</td>
<td>Cross-border</td>
<td>about USD 1.4 billion</td>
<td>people of Malaysia</td>
<td>U.S. forfeiture litigation + DOJ repatriation</td>
<td>U.S. Court of Appeals (9th Cir.) in related 1MDB-linked forfeiture action, <em>U.S. v. PetroSaudi Oil Services</em> (13 Jun 2023)<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> + DOJ repatriation release<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></td>
<td>Verified (official source + court decision)</td>
</tr>
</tbody>
</table>
</section>
<section id="court-decision-links-and-transfer-nexus-priority-cases" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="court-decision-links-and-transfer-nexus-priority-cases"><span class="header-section-number">4</span> Court Decision Links and Transfer Nexus (Priority Cases)</h2>
<section id="switzerland---nigeria-abacha" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="switzerland---nigeria-abacha"><span class="header-section-number">4.1</span> Switzerland -&gt; Nigeria (Abacha)</h3>
<ul>
<li><strong>Court decision:</strong> Swiss Federal Supreme Court, ATF 131 II 169 (case 1A.215/2004, 7 Feb 2005).<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></li>
<li><strong>Short summary:</strong> The Court addressed mutual legal assistance and asset return conditions in the Abacha matter, including transfer of funds under Swiss international cooperation law (IRSG) where criminal proceedings were ongoing in the requesting state.</li>
<li><strong>How this enabled transfer:</strong> The decision helped validate the Swiss legal path for releasing Abacha-linked assets under judicial cooperation rules. Later confiscation actions and the 2017 Switzerland-Nigeria-World Bank agreement then operationalized the actual monitored transfer.</li>
</ul>
</section>
<section id="u.s.---malaysia-1mdb" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="u.s.---malaysia-1mdb"><span class="header-section-number">4.2</span> U.S. -&gt; Malaysia (1MDB)</h3>
<ul>
<li><strong>Court decision:</strong> U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 and 22-55025, filed 13 Jun 2023.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></li>
<li><strong>Short summary:</strong> The Ninth Circuit affirmed district-court orders preserving and allowing seizure of assets in a civil forfeiture action tied to alleged 1MDB proceeds (including a USD 380 million arbitration fund).</li>
<li><strong>How this enabled transfer:</strong> By upholding protective/seizure authority over the res, the decision supported asset preservation and forfeiture progression, which is the legal precondition for later DOJ repatriation decisions such as the 2024 transfer tranche to Malaysia.</li>
</ul>
</section>
<section id="uk---nigeria-ibori" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="uk---nigeria-ibori"><span class="header-section-number">4.3</span> UK -&gt; Nigeria (Ibori)</h3>
<ul>
<li><strong>Court-linked source currently available:</strong> UK-Nigeria return annex confirming that returned funds were recovered through UK confiscation orders made since 2010.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></li>
<li><strong>Short summary:</strong> The annex is not itself a judicial decision but it is the key official legal instrument identifying the confiscation-order basis for the transfer.</li>
<li><strong>How this enabled transfer:</strong> The confiscation orders created recoverable value under UK law; the 2021 bilateral return framework then directed that value to specific monitored projects in Nigeria.</li>
<li><strong>Verification caveat:</strong> A full-text public copy of the underlying Southwark confiscation orders has not yet been located in open official databases.</li>
</ul>
</section>
</section>
<section id="case-template-completion-current-status" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="case-template-completion-current-status"><span class="header-section-number">5</span> Case Template Completion (Current Status)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Case</th>
<th>Crime type</th>
<th>Authority</th>
<th>Legal basis / instrument</th>
<th>Court decision link</th>
<th>Verification status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>U.S. -&gt; Madoff victims</td>
<td>Fraud / Ponzi scheme / money laundering proceeds</td>
<td>U.S. DOJ (MLARS) and appointed fund administration</td>
<td>U.S. forfeiture + DOJ victim fund distribution process</td>
<td>Not prioritized for this tranche</td>
<td>Verified</td>
</tr>
<tr class="even">
<td>U.S. -&gt; Western Union victims</td>
<td>Fraud facilitation and AML failures linked to consumer scams</td>
<td>U.S. DOJ</td>
<td>Forfeiture + remission process under DOJ administration</td>
<td>Not prioritized for this tranche</td>
<td>Verified</td>
</tr>
<tr class="odd">
<td>Switzerland -&gt; Nigeria (Abacha II)</td>
<td>Corruption / embezzlement / laundering of illicit state assets</td>
<td>Swiss prosecutorial and federal authorities; FDFA; World Bank (monitoring role)</td>
<td>Swiss confiscation framework + tripartite restitution agreement (2017)</td>
<td>ATF 131 II 169 (1A.215/2004)<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></td>
<td>Verified (strong)</td>
</tr>
<tr class="even">
<td>UK -&gt; Nigeria (Ibori)</td>
<td>Corruption and laundering-related proceeds linked to Ibori network</td>
<td>UK government authorities; Nigerian authorities</td>
<td>Confiscation orders (since 2010) + UK-Nigeria return annex (2021)</td>
<td>Annex confirms confiscation-order basis; full court order text pending</td>
<td>Verified with court-text gap</td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Malaysia (1MDB)</td>
<td>Large-scale misappropriation / bribery / money laundering</td>
<td>U.S. DOJ; U.S. federal courts</td>
<td>Civil forfeiture actions + DOJ repatriation decisions</td>
<td>Ninth Circuit decision in related forfeiture action<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></td>
<td>Verified (strong)</td>
</tr>
</tbody>
</table>
</section>
<section id="domestic-transfer-cases" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="domestic-transfer-cases"><span class="header-section-number">6</span> Domestic Transfer Cases</h2>
<section id="u.s.-madoff-victim-fund" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="u.s.-madoff-victim-fund"><span class="header-section-number">6.1</span> 1. U.S. Madoff Victim Fund</h3>
<p>This is one of the clearest public examples of <strong>forfeited assets being redistributed to victims at scale</strong>. On 30 December 2024, the U.S. Department of Justice announced the <strong>10th and final distribution</strong> of the Madoff Victim Fund. The Department stated that more than <strong>USD 4.3 billion</strong> in forfeited funds had been paid to <strong>40,930 victims in 127 countries</strong>, bringing aggregate recovery to <strong>93.71% of fraud losses</strong>.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<p>The legal step preceding the transfer was the U.S. government’s recovery of assets through <strong>civil and criminal forfeiture connected to the Bernard L. Madoff fraud scheme</strong>. The transfer mechanism was not an ad hoc political decision, but a formal DOJ-administered victim compensation structure.</p>
<p>Why it matters: this is a strong example of a <strong>domestic victim-compensation model</strong> built on forfeited assets rather than on ordinary restitution alone.</p>
</section>
<section id="u.s.-western-union-remission-fund" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="u.s.-western-union-remission-fund"><span class="header-section-number">6.2</span> 2. U.S. Western Union Remission Fund</h3>
<p>Western Union is another strong domestic model because the DOJ publicly explains both the <strong>forfeiture event</strong> and the <strong>distribution process</strong>. On 9 September 2024, DOJ announced that the Western Union Remission Fund had begun its second distribution in phase two, transferring approximately <strong>USD 18.5 million</strong> to around <strong>3,000 victims</strong>. DOJ stated that, across both phases, the fund had already distributed <strong>over USD 420 million</strong> to <strong>more than 175,000 victims</strong>, who received full compensation for their losses.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p>The official materials connect the transfer to <strong>funds forfeited to the United States from Western Union</strong>. The compensation mechanism was <strong>remission</strong>, a formal administrative process through which forfeited funds can be returned to victims.</p>
<p>Why it matters: this case shows that a transfer to victims can be structured even when the proceeds first pass through the state, provided there is a clear remission framework and a verified class of victims.</p>
</section>
</section>
<section id="cross-border-transfer-cases" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="cross-border-transfer-cases"><span class="header-section-number">7</span> Cross-Border Transfer Cases</h2>
<section id="switzerland---nigeria-abacha-ii" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="switzerland---nigeria-abacha-ii"><span class="header-section-number">7.1</span> 3. Switzerland -&gt; Nigeria (Abacha II)</h3>
<p>Switzerland’s return of Abacha assets is one of the best documented cross-border models. According to the Swiss Federal Department of Foreign Affairs, on <strong>4 December 2017</strong> Switzerland, Nigeria and the World Bank signed a <strong>tripartite agreement</strong> governing the restitution of approximately <strong>USD 321 million</strong> to Nigeria’s population.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
<p>The official Swiss explanation is important because it identifies the legal step that came before transfer: the funds had been <strong>repatriated and confiscated by Switzerland as part of criminal proceedings brought by the public prosecutor’s office of Geneva against Abba Abacha</strong>.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> A prior Swiss press release from <strong>8 March 2016</strong> states that the return process became possible after the <strong>Attorney General of the Canton of Geneva confiscated</strong> the assets.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p>The agreement did not authorize an unrestricted transfer to the Nigerian state budget. Instead, it required <strong>World Bank-supported monitoring</strong>, tranche-based disbursement, and anti-misuse safeguards. The World Bank’s own factsheet likewise describes the arrangement as a monitored repatriation process.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
<p>Why it matters: this is a leading example of <strong>confiscation plus monitored interstate restitution</strong>, which is likely more relevant for Ukraine than an unconditioned bilateral transfer.</p>
</section>
<section id="uk---nigeria-ibori-1" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="uk---nigeria-ibori-1"><span class="header-section-number">7.2</span> 4. UK -&gt; Nigeria (Ibori)</h3>
<p>On <strong>9 March 2021</strong>, the UK and Nigeria agreed the return of <strong>GBP 4.2 million</strong> recovered from associates of former Delta State Governor James Ibori.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> The official UK press release says the money would be used for Nigerian infrastructure and public-benefit projects, and that implementation would be subject to monitoring and audit.</p>
<p>The associated UK publication of the agreement’s annex is useful because it identifies the legal precursor to the transfer. It states that the returned funds were recovered in proceedings resulting in <strong>confiscation orders made since 2010</strong>.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a> It also restricts the use of the money to specified projects and bars disbursement to alleged perpetrators and related persons.</p>
<p>Why it matters: this is a concise example of <strong>confiscation orders plus a bilateral implementation agreement</strong>. The transfer did not follow automatically from confiscation; the bilateral arrangement operationalized the destination and controls.</p>
<p>Court-link status: this initial tranche confirms the confiscation-order basis from official UK materials, but a full-text public copy of the operative confiscation orders is still pending.</p>
</section>
<section id="u.s.---malaysia-1mdb-1" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="u.s.---malaysia-1mdb-1"><span class="header-section-number">7.3</span> 5. U.S. -&gt; Malaysia (1MDB)</h3>
<p>The U.S. Department of Justice provides unusually clear official reporting on the repatriation of 1MDB proceeds. On <strong>13 June 2024</strong>, DOJ announced an additional <strong>USD 156 million</strong> repatriation to Malaysia, bringing the total returned by DOJ to approximately <strong>USD 1.4 billion</strong>.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></p>
<p>DOJ links these returns to the long-running U.S. forfeiture campaign involving 1MDB proceeds. The Department states that, since July 2016, it had filed <strong>41 civil forfeiture actions</strong> and seized more than <strong>USD 1.7 billion</strong> in assets allegedly traceable to the scheme.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></p>
<p>A published judicial layer is available in a related forfeiture track: in <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em> (Ninth Circuit, 13 June 2023), the court affirmed interlocutory orders preserving and permitting seizure of assets allegedly connected to 1MDB proceeds.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a> This did not itself order repatriation to Malaysia, but it upheld legal control over assets in the forfeiture pipeline that is necessary before transfer decisions.</p>
<p>Why it matters: 1MDB shows that large cross-border returns are possible, but only after a lengthy forfeiture phase, substantial tracing work, and a dedicated repatriation decision by the recovering state.</p>
</section>
</section>
<section id="switzerland-as-a-leading-model" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="switzerland-as-a-leading-model"><span class="header-section-number">8</span> Switzerland as a Leading Model</h2>
<p>Management specifically mentioned Switzerland, and the official materials strongly support that focus.</p>
<p>The Swiss Federal Department of Foreign Affairs states that Switzerland has returned <strong>more than USD 2 billion</strong> to countries of origin pursuant to restitution agreements.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a> The State Secretariat for International Finance similarly states that, over roughly three decades, Switzerland has returned <strong>more than USD 2 billion</strong> for the benefit of affected populations in countries including Nigeria, the Philippines, Peru, Angola and Kazakhstan.<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></p>
<p>Swiss official materials also show that Switzerland does not rely on a single model. At least three variants appear in practice:</p>
<ul>
<li><strong>Direct restitution linked to prior confiscation</strong>, but governed by a specific agreement.</li>
<li><strong>Tripartite arrangements with international organizations</strong>, especially the World Bank.</li>
<li><strong>Return through a trust fund or special vehicle</strong> designed to benefit the population rather than the political elite.</li>
</ul>
<p>Two additional Swiss cases are especially relevant:</p>
<section id="switzerland---kazakhstan" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="switzerland---kazakhstan"><span class="header-section-number">8.1</span> Switzerland -&gt; Kazakhstan</h3>
<p>In <strong>2012</strong>, Switzerland and the World Bank signed an agreement to return <strong>USD 48 million</strong> in assets to Kazakhstan for public-benefit projects.<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a> The Swiss press release states that the funds had been <strong>confiscated in 2011</strong> in criminal proceedings initiated by Geneva judicial authorities on suspicion of money laundering.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a></p>
<p>Switzerland’s later official retrospective on Kazakhstan states that an earlier <strong>USD 115 million</strong> restitution had been completed through the <strong>BOTA Kazakh Child and Youth Development Foundation</strong>, established by Switzerland, the United States and Kazakhstan in 2007.<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a></p>
</section>
<section id="switzerland---peru" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="switzerland---peru"><span class="header-section-number">8.2</span> Switzerland -&gt; Peru</h3>
<p>In <strong>December 2020</strong>, Switzerland signed a trilateral agreement with Peru and Luxembourg to return approximately <strong>USD 16.3 million</strong> from Switzerland and around <strong>EUR 9.7 million</strong> from Luxembourg for projects strengthening the rule of law and anti-corruption capacity in Peru.<a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a> Swiss materials explain that these funds could be returned after <strong>further confiscation procedures had recently been concluded</strong>.<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a></p>
</section>
</section>
<section id="preliminary-implications-for-ukraine" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="preliminary-implications-for-ukraine"><span class="header-section-number">9</span> Preliminary Implications for Ukraine</h2>
<p>The initial cases point to four practical lessons.</p>
<section id="final-confiscation-is-necessary-but-not-sufficient" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="final-confiscation-is-necessary-but-not-sufficient"><span class="header-section-number">9.1</span> 1. Final confiscation is necessary, but not sufficient</h3>
<p>In the cross-border cases reviewed, confiscation or forfeiture was the legal trigger, but <strong>another instrument</strong> was usually needed before the money could be transferred to the ultimate beneficiary.</p>
</section>
<section id="monitoring-architecture-is-central" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="monitoring-architecture-is-central"><span class="header-section-number">9.2</span> 2. Monitoring architecture is central</h3>
<p>The Swiss and UK examples show that where the receiving state raises governance concerns, the returning state often insists on:</p>
<ul>
<li>project earmarking;</li>
<li>tranche-based release;</li>
<li>independent monitoring;</li>
<li>civil-society or international-organization oversight.</li>
</ul>
</section>
<section id="switzerland-is-useful-not-just-because-of-volume-but-because-of-design" class="level3" data-number="9.3">
<h3 data-number="9.3" class="anchored" data-anchor-id="switzerland-is-useful-not-just-because-of-volume-but-because-of-design"><span class="header-section-number">9.3</span> 3. Switzerland is useful not just because of volume, but because of design</h3>
<p>The official Swiss materials are especially valuable because they explain the <strong>institutional logic</strong> of asset return: restitution agreements, anti-corruption safeguards, and use of the returned funds for the benefit of the population rather than the state elite.</p>
</section>
<section id="germany-remains-important-but-public-transfer-cases-are-harder-to-document" class="level3" data-number="9.4">
<h3 data-number="9.4" class="anchored" data-anchor-id="germany-remains-important-but-public-transfer-cases-are-harder-to-document"><span class="header-section-number">9.4</span> 4. Germany remains important, but public transfer cases are harder to document</h3>
<p>Germany has a statutory victim-compensation route after confiscation under <strong>StPO §§ 459h-459m</strong>.<a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a><a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a> However, publicly accessible, well-documented <strong>completed transfer cases</strong> are less visible than in the U.S., UK or Swiss materials. For the next research tranche, Germany should be investigated through:</p>
<ul>
<li>published enforcement decisions;</li>
<li>prosecutor notices to injured parties;</li>
<li>court decisions on objections under the confiscation enforcement provisions; and</li>
<li>large public cases where injured state entities sought distribution from confiscated proceeds.</li>
</ul>
</section>
</section>
<section id="scope-confirmation-needed-from-management" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="scope-confirmation-needed-from-management"><span class="header-section-number">10</span> Scope Confirmation Needed From Management</h2>
<p>To avoid producing two parallel tracks, the following point should be confirmed with management:</p>
<p><strong>Should <code>German_Sanctions_Criminal_Asset_Pipeline_3Page</code> now be fully rewritten into this case-based asset-transfer structure, or should it remain as the Germany-focused operational memo while this new case-based note develops separately?</strong></p>
<p>Suggested one-line message:</p>
<blockquote class="blockquote">
<p>Please confirm whether we should fully replace the current Germany criminal-asset pipeline memo with the cross-jurisdiction transfer-case format, or keep the Germany memo as-is and treat the transfer-case document as a separate deliverable.</p>
</blockquote>
</section>
<section id="conclusion" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">11</span> Conclusion</h2>
<p>The initial research confirms that the strongest precedents for asset transfer are <strong>case-specific and mechanism-specific</strong>. Domestic transfers are most clearly documented in the U.S. through forfeiture-based victim compensation. Cross-border transfers are most clearly documented in <strong>Switzerland</strong>, the <strong>UK</strong>, and the <strong>U.S.</strong> where confiscation is followed by a separate restitution or repatriation mechanism.</p>
<p>For Ukraine-oriented work, the Swiss and UK models are especially important because they show how confiscated assets can be redirected to public benefit <strong>without relying on an unrestricted budget transfer</strong>. The most realistic analogue is therefore not simple seizure-to-transfer, but <strong>final confiscation plus a monitored allocation agreement</strong>.</p>
</section>
<section id="official-sources-used" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="official-sources-used"><span class="header-section-number">12</span> Official Sources Used</h2>
<ul>
<li>DOJ, Madoff Victim Fund, 30 Dec 2024.<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a></li>
<li>DOJ, Western Union Remission Fund, 9 Sep 2024.<a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a></li>
<li>Swiss FDFA, Abacha II tripartite agreement, 4 Dec 2017.<a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a></li>
<li>Swiss FDFA, Abacha letter of intent, 8 Mar 2016.<a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a></li>
<li>World Bank, monitoring of repatriated Abacha funds, 4 Dec 2017.<a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a></li>
<li>GOV.UK, UK -&gt; Nigeria return announcement, 9 Mar 2021.<a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a></li>
<li>GOV.UK, annex on Ibori returned funds and confiscation orders.<a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a></li>
<li>DOJ, 1MDB repatriation, 13 Jun 2024.<a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a></li>
<li>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, 13 Jun 2023.<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a></li>
<li>Swiss Federal Supreme Court, ATF 131 II 169 (1A.215/2004), 7 Feb 2005.<a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a></li>
<li>Swiss FDFA, asset recovery and return of illicit PEP assets.<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a></li>
<li>Swiss SIF, illicit financial flows / asset recovery page.<a href="#fn44" class="footnote-ref" id="fnref44" role="doc-noteref"><sup>44</sup></a></li>
<li>Swiss FDFA, Kazakhstan restitution materials.<a href="#fn45" class="footnote-ref" id="fnref45" role="doc-noteref"><sup>45</sup></a><a href="#fn46" class="footnote-ref" id="fnref46" role="doc-noteref"><sup>46</sup></a></li>
<li>Swiss FDFA, Peru trilateral restitution materials.<a href="#fn47" class="footnote-ref" id="fnref47" role="doc-noteref"><sup>47</sup></a><a href="#fn48" class="footnote-ref" id="fnref48" role="doc-noteref"><sup>48</sup></a></li>
</ul>
</section>
<section id="link-spot-check-5-march-2026" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="link-spot-check-5-march-2026"><span class="header-section-number">13</span> Link Spot-Check (5 March 2026)</h2>
<p>All currently cited official links in this note were live-checked and returned <strong>HTTP 200</strong> on 5 March 2026, including DOJ, Swiss FDFA, World Bank, GOV.UK, and German legal texts.</p>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>U.S. Department of Justice, “Justice Department’s 10th Distribution Brings Total Provided to Over $4.3B in Nearly Full Recovery to Over 40,000 Victims in Madoff Ponzi Scheme”, 30 Dec 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery" class="uri">https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>U.S. Department of Justice, “Justice Department Begins Second Distribution of Forfeited Funds to Compensate Victims of Fraud Scheme Facilitated by Western Union”, 9 Sep 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>U.S. Department of Justice, “Justice Department’s 10th Distribution Brings Total Provided to Over $4.3B in Nearly Full Recovery to Over 40,000 Victims in Madoff Ponzi Scheme”, 30 Dec 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery" class="uri">https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>U.S. Department of Justice, “Justice Department Begins Second Distribution of Forfeited Funds to Compensate Victims of Fraud Scheme Facilitated by Western Union”, 9 Sep 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud</a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>Swiss FDFA, “Asset Recovery in cases of foreign politically exposed persons (PEPs)”, accessed 4 Mar 2026, <a href="https://www.eda.admin.ch/eda/en/home/foreign-policy/international-law/unrechtmaessig-erworbene-gelder.html" class="uri">https://www.eda.admin.ch/eda/en/home/foreign-policy/international-law/unrechtmaessig-erworbene-gelder.html</a>.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>Swiss State Secretariat for International Finance, “How Switzerland supports the fight against financial crime, corruption and tax evasion, and works in the area of asset recovery”, accessed 4 Mar 2026, <a href="https://www.sif.admin.ch/en/illicit-financial-flows-2" class="uri">https://www.sif.admin.ch/en/illicit-financial-flows-2</a>.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p>Swiss FDFA, “Trilateral agreement: Switzerland and Luxembourg to return illicitly acquired assets to Peru”, 16 Dec 2020, <a href="https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674" class="uri">https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674</a>.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p>German Federal Ministry of Justice, StPO § 459h, <a href="https://www.gesetze-im-internet.de/stpo/__459h.html" class="uri">https://www.gesetze-im-internet.de/stpo/__459h.html</a>.<a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p>German Federal Ministry of Justice, StPO § 459o, <a href="https://www.gesetze-im-internet.de/stpo/__459o.html" class="uri">https://www.gesetze-im-internet.de/stpo/__459o.html</a>.<a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p>U.S. Department of Justice, “Justice Department’s 10th Distribution Brings Total Provided to Over $4.3B in Nearly Full Recovery to Over 40,000 Victims in Madoff Ponzi Scheme”, 30 Dec 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery" class="uri">https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery</a>.<a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p>U.S. Department of Justice, “Justice Department Begins Second Distribution of Forfeited Funds to Compensate Victims of Fraud Scheme Facilitated by Western Union”, 9 Sep 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud</a>.<a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p>Swiss FDFA, “Asset Recovery in cases of foreign politically exposed persons (PEPs)”, accessed 4 Mar 2026, <a href="https://www.eda.admin.ch/eda/en/home/foreign-policy/international-law/unrechtmaessig-erworbene-gelder.html" class="uri">https://www.eda.admin.ch/eda/en/home/foreign-policy/international-law/unrechtmaessig-erworbene-gelder.html</a>.<a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn44"><p>Swiss State Secretariat for International Finance, “How Switzerland supports the fight against financial crime, corruption and tax evasion, and works in the area of asset recovery”, accessed 4 Mar 2026, <a href="https://www.sif.admin.ch/en/illicit-financial-flows-2" class="uri">https://www.sif.admin.ch/en/illicit-financial-flows-2</a>.<a href="#fnref44" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn45"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref45" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn46"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref46" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn47"><p>Swiss FDFA, “Trilateral agreement: Switzerland and Luxembourg to return illicitly acquired assets to Peru”, 16 Dec 2020, <a href="https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674" class="uri">https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674</a>.<a href="#fnref47" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn48"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref48" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>