<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Artem Radin">
<meta name="dcterms.date" content="2026-04-07">

<title>Asset Transfer Cases: Second Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Asset_Transfer_Cases_2nd_Research_files/libs/clipboard/clipboard.min.js"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/popper.min.js"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/anchor.min.js"></script>
<link href="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Asset_Transfer_Cases_2nd_Research_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_2nd_Research_files/libs/bootstrap/bootstrap-66f220744880a257c6c06aa45740e4a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="mermaid-theme" content="neutral">
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="Asset_Transfer_Cases_2nd_Research_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="styles/summary.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose"><span class="header-section-number">1</span> Purpose</a></li>
  <li><a href="#working-pattern" id="toc-working-pattern" class="nav-link" data-scroll-target="#working-pattern"><span class="header-section-number">2</span> Working Pattern</a></li>
  <li><a href="#baseline-pathways-from-initial-research" id="toc-baseline-pathways-from-initial-research" class="nav-link" data-scroll-target="#baseline-pathways-from-initial-research"><span class="header-section-number">3</span> Baseline pathways from initial research</a></li>
  <li><a href="#interstate-case-matrix" id="toc-interstate-case-matrix" class="nav-link" data-scroll-target="#interstate-case-matrix"><span class="header-section-number">4</span> Interstate Case Matrix</a></li>
  <li><a href="#priority-case-analysis" id="toc-priority-case-analysis" class="nav-link" data-scroll-target="#priority-case-analysis"><span class="header-section-number">5</span> Priority Case Analysis</a></li>
  <li><a href="#preliminary-comparative-lessons-for-ukraine" id="toc-preliminary-comparative-lessons-for-ukraine" class="nav-link" data-scroll-target="#preliminary-comparative-lessons-for-ukraine"><span class="header-section-number">6</span> Preliminary Comparative Lessons For Ukraine</a></li>
  <li><a href="#tentative-conclusion" id="toc-tentative-conclusion" class="nav-link" data-scroll-target="#tentative-conclusion"><span class="header-section-number">7</span> Tentative Conclusion</a></li>
  <li><a href="#sources-7" id="toc-sources-7" class="nav-link" data-scroll-target="#sources-7"><span class="header-section-number">8</span> Sources</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Asset_Transfer_Cases_2nd_Research.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Asset Transfer Cases: Second Research</h1>
<p class="subtitle lead">Additional Interstate Models for Post-Confiscation Transfer</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Artem Radin </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Intern
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="purpose"><span class="header-section-number">1</span> Purpose</h2>
<p>This second note continues the first asset-transfer memo but shifts to <strong>new interstate cases not already substantially covered in the project</strong>. The focus remains on <strong>actual post-confiscation or post-forfeiture transfers</strong>, not merely freezing or seizure.</p>
<p>The main question is practical and Ukraine-oriented: <strong>which legal structures have allowed one state to transfer criminally confiscated assets to another state or to a monitored public-benefit vehicle, and which of those structures could inform a future Ukraine model?</strong></p>
<p>This draft follows the same logic as the first memo:</p>
<ul>
<li>identify the accusation and the parties;</li>
<li>trace the legal step that made transfer possible;</li>
<li>identify the legal basis for the return;</li>
<li>record how the returned assets were used;</li>
<li>assess whether monitoring, conditionality, or a joint project made the transfer politically and legally workable.</li>
</ul>
</section>
<section id="working-pattern" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="working-pattern"><span class="header-section-number">2</span> Working Pattern</h2>
<p>The strongest interstate return cases usually have four elements:</p>
<ol type="1">
<li>a <strong>final forfeiture, confiscation, or remission decision</strong> in the recovering state;</li>
<li>a <strong>second allocation instrument</strong> directing the assets to the receiving state or fund;</li>
<li>a <strong>public-benefit use restriction</strong> rather than an unrestricted treasury payment;</li>
<li>a <strong>monitoring architecture</strong> strong enough to answer misuse concerns.</li>
</ol>
<p>For Ukraine, the most useful cases are therefore not simply large returns. They are cases where confiscated value was channeled through a <strong>trust fund, monitored project vehicle, independent auditor, civil-society oversight mechanism, or multistate agreement</strong>.</p>
<div class="cell" data-fig-width="5.2" data-fig-height="4.2" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 32, 'nodeSpacing': 28}}}%%
flowchart TB
    A["Final forfeiture, confiscation, or remission in the recovering state"]
    B["Second allocation instrument — MoU, agreement, remission, or trust fund vehicle"]
    C["Public-benefit use restriction — not an unrestricted treasury transfer"]
    D["Monitoring architecture — audit, reporting, CSO or multilateral oversight"]
    A --&gt; B --&gt; C --&gt; D
</pre>
</div>
<p></p><figcaption> Generic interstate return pattern (applied across the case studies below)</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="baseline-pathways-from-initial-research" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="baseline-pathways-from-initial-research"><span class="header-section-number">3</span> Baseline pathways from initial research</h2>
<p>The first memo (<em>Asset Transfer Cases: Initial Research</em>) developed detailed pathway diagrams for three anchor cases. They are included here so this second note can be read together with the same visual architecture; citations and full case narrative for these matters remain in that document.</p>
<section id="switzerland-nigeria-abacha-ii" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="switzerland-nigeria-abacha-ii"><span class="header-section-number">3.1</span> Switzerland → Nigeria (Abacha II)</h3>
<div class="cell" data-fig-width="5.8" data-fig-height="7.2" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 40, 'nodeSpacing': 30}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        A1["Step 1: Nigeria submits MLA request to Switzerland&lt;br/&gt;for Abacha-linked assets held in Swiss banks"]
        A2["Step 2: Swiss authorities conduct IRSG admissibility review&lt;br/&gt;assess cooperation conditions under mutual legal assistance"]
        A3["Step 3: Swiss Federal Supreme Court ATF 131 II 169&lt;br/&gt;7 Feb 2005 — confirms legal parameters for cooperation and return"]
        A4["Step 4: Geneva prosecutor initiates criminal proceedings&lt;br/&gt;against Abba Abacha and related parties"]
        A5["Step 5: Swiss court Dec 2014: repatriation conditional on&lt;br/&gt;World Bank monitoring of use of funds"]
        A6["Step 6: Geneva Attorney General confiscates assets&lt;br/&gt;8 Mar 2016 — return process becomes legally possible"]
        A7["Step 7: Nigeria designates use: National Social Safety Net Project&lt;br/&gt;targeted cash transfers to poor and vulnerable Nigerians"]
        A8["Step 8: 4 Dec 2017: Tripartite MOU signed&lt;br/&gt;Switzerland, Nigeria, World Bank — USD 321 million"]
        A9["Step 9: Tranche-based disbursement to Nigeria&lt;br/&gt;funds applied to National Social Safety Net Project"]
        A10["Step 10: Cash transfers to beneficiaries&lt;br/&gt;poor and vulnerable Nigerians via IDA-financed project"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        M1["World Bank: monitors use of funds&lt;br/&gt;same manner as IDA Credit for National Social Safety Net Project"]
        M2["Nigerian CSOs under Network on Asset Recovery&lt;br/&gt;expertise in anti-corruption and asset recovery"]
        M3["CSOs monitor cash-to-beneficiaries&lt;br/&gt;bi-annual reports on use of funds"]
        M4["Transparency and accountability framework&lt;br/&gt;civil society oversight per tripartite agreement"]
    end

    A1 --&gt; A2 --&gt; A3 --&gt; A4 --&gt; A5 --&gt; A6 --&gt; A7 --&gt; A8 --&gt; A9 --&gt; A10
    A8 -.-&gt;|"enables"| M1
    A9 -.-&gt;|"subject to"| M2
    M2 --&gt; M3
    M1 --&gt; M4
    M3 --&gt; M4

    A1 -.-&gt; NA1
    A2 -.-&gt; NA2
    A3 -.-&gt; NA3
    A4 -.-&gt; NA4
    A5 -.-&gt; NA5
    A6 -.-&gt; NA6
    A7 -.-&gt; NA7
    A8 -.-&gt; NA8
    A9 -.-&gt; NA9
    A10 -.-&gt; NA10

    NA1["MLA request under Swiss IRSG Bundesgesetz über internationale Rechtshilfe in Strafsachen; assets traced to late Gen. Sani Abacha and family in Swiss banks; Nigeria as requesting state."]
    NA2["OFJ and cantonal authorities assessed admissibility under IRSG Art. 3; dual criminality and cooperation conditions reviewed."]
    NA3["ATF 131 II 169 7 Feb 2005 case 1A.215/2004; confirmed MLA and return parameters under IRSG while proceedings ongoing in Nigeria."]
    NA4["Procureur général de Genève initiated criminal proceedings against Abba Abacha; assets identified, frozen under Swiss criminal procedure."]
    NA5["Dec 2014 Swiss court ruling: repatriation conditional on World Bank monitoring of use; precondition for transfer."]
    NA6["8 Mar 2016 Procureur général Genève confiscation order; assets transferred to Swiss Confederation under Art. 69-72 SCC."]
    NA7["Nigeria designated National Social Safety Net Project P151488; IDA Credit; targeted cash transfers to poor households."]
    NA8["4 Dec 2017 tripartite MOU: Federal Govt Nigeria, Swiss Federal Council, World Bank; disbursement modalities and WB monitoring role."]
    NA9["Tranche-based release; funds applied to IDA-financed National Social Safety Net Project; same monitoring as IDA Credit."]
    NA10["Cash to beneficiaries; NAR CSOs monitor cash-to-beneficiaries; bi-annual reports per tripartite agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NA1,NA2,NA3,NA4,NA5,NA6,NA7,NA8,NA9,NA10 noteBox
</pre>
</div>
<p></p><figcaption> Switzerland–Nigeria (Abacha II): MLA, confiscation, tripartite MOU, and monitoring (initial research)</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="u.s.-malaysia-1mdb" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="u.s.-malaysia-1mdb"><span class="header-section-number">3.2</span> U.S. → Malaysia (1MDB)</h3>
<div class="cell" data-fig-width="5.8" data-fig-height="6.8" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 40, 'nodeSpacing': 30}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        B1["Step 1: DOJ initiates civil forfeiture actions&lt;br/&gt;from Jul 2016 — 41 actions targeting 1MDB-linked assets"]
        B2["Step 2: U.S. district courts order restraint and seizure&lt;br/&gt;preservation of res during litigation"]
        B3["Step 3: Ninth Circuit affirms seizure-preservation orders&lt;br/&gt;13 Jun 2023 — PetroSaudi-related track upheld"]
        B4["Step 4: Forfeiture pipeline: settlements and dispositions&lt;br/&gt;assets converted to recoverable value under U.S. law"]
        B5["Step 5: DOJ repatriation tranche decisions&lt;br/&gt;executive/legal-policy determination for Malaysia"]
        B6["Step 6: Transfer to Malaysia 1MDB Asset Recovery Trust Account&lt;br/&gt;e.g. USD 452m Aug 2021, USD 156m Jun 2024 — total ~USD 1.4bn"]
        B7["Step 7: Funds for benefit of people of Malaysia&lt;br/&gt;administered via Malaysian trust vehicle"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        N1["Malaysian 1MDB Asset Recovery Trust Account&lt;br/&gt;designated vehicle for repatriated proceeds"]
        N2["Trust account administration&lt;br/&gt;use for public benefit per agreement"]
        N3["Bilateral U.S.–Malaysia repatriation framework&lt;br/&gt;tranche-based returns with designated destination"]
    end

    B1 --&gt; B2 --&gt; B3 --&gt; B4 --&gt; B5 --&gt; B6 --&gt; B7
    B5 -.-&gt;|"governs"| N1
    B6 -.-&gt;|"to"| N1
    N1 --&gt; N2
    N2 --&gt; N3

    B1 -.-&gt; NB1
    B2 -.-&gt; NB2
    B3 -.-&gt; NB3
    B4 -.-&gt; NB4
    B5 -.-&gt; NB5
    B6 -.-&gt; NB6
    B7 -.-&gt; NB7

    NB1["41 in rem civil forfeiture actions under 18 USC 981 from Jul 2016; Kleptocracy Asset Recovery Initiative; assets traceable to 1MDB."]
    NB2["District court restraining orders and warrants of arrest in rem; 18 USC 981; res preserved pending forfeiture litigation."]
    NB3["9th Cir. U.S. v. PetroSaudi Oil Services Nos. 21-56228 22-55025 13 Jun 2023; affirmed interlocutory orders; USD 380m arbitration fund."]
    NB4["Settlements and default judgments under 18 USC 981; assets converted to recoverable value; DOJ disposition authority."]
    NB5["DOJ MLARS repatriation decision; assets legally forfeited; tranche determination under bilateral U.S.-Malaysia framework."]
    NB6["Wire to 1MDB Asset Recovery Trust Account; USD 452m Aug 2021, USD 156m Jun 2024; total ~USD 1.4bn per DOJ."]
    NB7["Trust account administered for benefit of people of Malaysia; designated recipient per bilateral repatriation agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NB1,NB2,NB3,NB4,NB5,NB6,NB7 noteBox
</pre>
</div>
<p></p><figcaption> U.S. → Malaysia (1MDB): forfeiture pipeline, trust account, and repatriation framework (initial research)</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="uk-nigeria-ibori" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="uk-nigeria-ibori"><span class="header-section-number">3.3</span> UK → Nigeria (Ibori)</h3>
<div class="cell" data-fig-width="5.8" data-fig-height="6.8" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 40, 'nodeSpacing': 30}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        C1["Step 1: UK investigation: Met Police, NCA, CPS&lt;br/&gt;Ibori network — money laundering, fraud, forgery"]
        C2["Step 2: Feb 2012: Ibori pleads guilty in UK court&lt;br/&gt;13 years imprisonment"]
        C3["Step 3: UK confiscation orders since 2010&lt;br/&gt;recoverable criminal property value established"]
        C4["Step 4: UK–Nigeria return negotiations&lt;br/&gt;framework for destination and safeguards"]
        C5["Step 5: 9 Mar 2021: UK–Nigeria agreement and annex signed&lt;br/&gt;GBP 4.2 million — project use and oversight conditions"]
        C6["Step 6: Transfer of GBP 4.2m to Nigeria&lt;br/&gt;under bilateral MoU"]
        C7["Step 7: Projects: Lagos–Ibadan Expressway, Abuja–Kano road&lt;br/&gt;second Niger Bridge — infrastructure and public benefit"]
        C8["Step 8: Nigeria Sovereign Investment Authority&lt;br/&gt;administers project implementation"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        O1["Cleen Foundation: independent monitoring&lt;br/&gt;expertise in infrastructure, anti-corruption, procurement"]
        O2["Federal Republic of Nigeria Monitoring Team&lt;br/&gt;oversees implementation, regular progress reporting"]
        O3["Budget plan and work/expenditure schedule&lt;br/&gt;per project, agreed by UK and Nigerian representatives"]
        O4["Annual accountability reports&lt;br/&gt;published, information to Nigerian public"]
        O5["Bar on disbursement to perpetrators&lt;br/&gt;and related persons per annex"]
    end

    C1 --&gt; C2 --&gt; C3 --&gt; C4 --&gt; C5 --&gt; C6 --&gt; C7 --&gt; C8
    C5 -.-&gt;|"requires"| O1
    C6 -.-&gt;|"subject to"| O2
    O1 --&gt; O3
    O2 --&gt; O4
    O3 --&gt; O5
    O4 --&gt; O5

    C1 -.-&gt; NC1
    C2 -.-&gt; NC2
    C3 -.-&gt; NC3
    C4 -.-&gt; NC4
    C5 -.-&gt; NC5
    C6 -.-&gt; NC6
    C7 -.-&gt; NC7
    C8 -.-&gt; NC8

    NC1["Met Police Proceeds of Crime Unit, NCA, CPS; POCA 2002; money laundering s.327, conspiracy to defraud, forgery; Ibori network."]
    NC2["Southwark Crown Court Feb 2012; Ibori guilty plea; 13 years; confiscation proceedings under POCA s.6 followed."]
    NC3["Confiscation orders under POCA s.6 since 2010; recoverable amount and criminal property value; annex confirms order basis."]
    NC4["UK-Nigeria negotiations under 2016 MoU; return framework; destination, project earmarking, audit safeguards."]
    NC5["9 Mar 2021 UK-Nigeria agreement and annex; GBP 4.2m; budget plan and work schedule per project; bar on perpetrator disbursement."]
    NC6["Transfer under bilateral MoU; first return under 2016 framework; funds to NSIA for designated projects."]
    NC7["Earmarked: Lagos-Ibadan Expressway, Abuja-Kano road, second Niger Bridge; infrastructure and public benefit."]
    NC8["NSIA administers; Cleen Foundation independent monitoring; Federal Monitoring Team; annual accountability reports to public."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NC1,NC2,NC3,NC4,NC5,NC6,NC7,NC8 noteBox
</pre>
</div>
<p></p><figcaption> UK → Nigeria (Ibori): conviction, confiscation, bilateral return, NSIA projects (initial research)</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="interstate-case-matrix" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="interstate-case-matrix"><span class="header-section-number">4</span> Interstate Case Matrix</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 2%">
<col style="width: 13%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Case</th>
<th>Accusation / predicate offense</th>
<th>Parties</th>
<th>Forum / decision date</th>
<th>Amount</th>
<th>Legal basis for confiscation / forfeiture</th>
<th>Legal basis for return</th>
<th>Recipient / use of funds</th>
<th>Monitoring / joint project</th>
<th>Why it matters for Ukraine</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Switzerland -&gt; Uzbekistan (Karimova)</td>
<td>Bribery and laundering linked to telecom contracts involving Gulnara Karimova</td>
<td>Switzerland, Uzbekistan, UN</td>
<td>Framework agreement 11 Sep 2020; restitution agreement 16 Aug 2022</td>
<td>USD 131 million initially, plus future definitively confiscated assets</td>
<td>Swiss criminal proceedings and definitive confiscation</td>
<td>Switzerland-Uzbekistan restitution agreement; UN Multi-Partner Trust Fund</td>
<td>Benefit of population of Uzbekistan; health and social-development programming</td>
<td>UN trust fund governance; joint strategic bodies; civil-society consultative role</td>
<td>Best recent model for using a neutral international vehicle instead of direct budget transfer</td>
</tr>
<tr class="even">
<td>U.S. / Jersey -&gt; Nigeria (Abacha, 2020 tranche)</td>
<td>Embezzlement, misappropriation, extortion, laundering of Abacha proceeds</td>
<td>U.S., Jersey, Nigeria</td>
<td>D.D.C. forfeiture judgment 2014; trilateral agreement 3 Feb 2020; transfer 4 May 2020</td>
<td>USD 311.8 million transferred</td>
<td>U.S. civil forfeiture judgment enforced in Jersey</td>
<td>Trilateral repatriation agreement</td>
<td>Public-benefit projects in Nigeria</td>
<td>Safeguards in agreement; implementation and accountability conditions</td>
<td>Strong model for allied-jurisdiction enforcement of one state’s forfeiture judgment</td>
</tr>
<tr class="odd">
<td>U.S. / UK -&gt; Nigeria (Abacha, 2022 tranche)</td>
<td>Same Abacha corruption proceeds, with assets located in the UK</td>
<td>U.S., UK, Nigeria</td>
<td>D.D.C. forfeiture judgment 2014; U.S.-Nigeria agreement 23 Aug 2022; transfer 17 Nov 2022</td>
<td>Over USD 20.6 million transferred, from roughly USD 23 million forfeited</td>
<td>U.S. forfeiture judgment; UK enforcement cooperation</td>
<td>Bilateral U.S.-Nigeria repatriation agreement</td>
<td>Second Niger Bridge, Lagos-Ibadan Expressway, Abuja-Kano road</td>
<td>NSIA administration, independent audit, civil-society monitoring</td>
<td>Useful precedent for repeated repatriation under a prior forfeiture case</td>
</tr>
<tr class="even">
<td>U.S. -&gt; Nigeria (Alison-Madueke / Aluko-Omokore)</td>
<td>Bribery in Nigerian oil contracts, laundering through U.S. assets including luxury real estate and yacht</td>
<td>U.S., Nigeria, World Bank trust-fund structure, IIJ</td>
<td>Agreement signed 10 Jan 2025</td>
<td>USD 52.88 million</td>
<td>U.S. forfeiture proceedings tied to corruption and laundering</td>
<td>U.S.-Nigeria transfer agreement; forfeiture-sharing authority under U.S. law</td>
<td>USD 50m for electrification through a World Bank trust fund; about USD 2.88m for IIJ rule-of-law and counter-terrorism work</td>
<td>World Bank oversight, auditing, publication requirements, external reporting</td>
<td>Very strong analogue for Ukraine because assets were split between reconstruction-style spending and institutional capacity-building</td>
</tr>
<tr class="odd">
<td>Jersey -&gt; Kenya (Windward / Gichuru-Okemo)</td>
<td>Corruption proceeds linked to contracts awarded by Kenya Power and Lighting Company</td>
<td>Jersey, Kenya, UK, Switzerland</td>
<td>Jersey confiscation 24 Feb 2016; bilateral step 3 Mar 2017; FRACCK signed Dec 2018; ARA signed 28 Mar 2022</td>
<td>About GBP 3 million returned</td>
<td>Royal Court confiscation order after guilty plea by Windward Trading Ltd</td>
<td>Asset Recovery Agreement under FRACCK framework</td>
<td>Kenya’s COVID-19 response; broader Vision 2030 development framing</td>
<td>FRACCK multilateral framework; asset-return principles agreed among partners</td>
<td>Strong precedent for framework-based asset return rather than one-off diplomacy</td>
</tr>
<tr class="even">
<td>Jersey -&gt; Mozambique (Fragoso)</td>
<td>Bribe proceeds linked to public-works contracts in Mozambique, hidden through Jersey trust structure</td>
<td>Jersey, Mozambique</td>
<td>Forfeiture proceedings under Jersey law; MoU signed 7 May 2024</td>
<td>Over GBP 829,500</td>
<td>Forfeiture of Assets (Civil Proceedings) (Jersey) Law 2018</td>
<td>Jersey-Mozambique Memorandum of Understanding</td>
<td>Building Mozambique’s asset-recovery and anti-corruption institutions</td>
<td>Earmarked institutional uses; training and agency support</td>
<td>Useful for Ukraine if part of future returns is directed to enforcement and recovery institutions</td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Kyrgyz Republic (Bakiyev)</td>
<td>Theft of state funds and corruption by former regime, traced into U.S. wire-fraud and insider-trading case proceeds</td>
<td>U.S., Kyrgyz Republic</td>
<td>EDNY forfeiture order; remission granted 4 Oct 2018; repatriation announced 26 Feb 2019</td>
<td>Approx. USD 4.6 million repatriated (of USD 6 million forfeiture order)</td>
<td>Criminal forfeiture order in U.S. case; DOJ remission decision</td>
<td>Petition for remission granted by DOJ MLARS</td>
<td>Healthcare equipment, drinking-water facilities, anti-corruption and judicial-transparency projects</td>
<td>Government commitments on end use; public joint statement</td>
<td>Demonstrates a foreign state’s use of remission to claim proceeds tied to stolen public funds</td>
</tr>
</tbody>
</table>
</section>
<section id="priority-case-analysis" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="priority-case-analysis"><span class="header-section-number">5</span> Priority Case Analysis</h2>
<section id="switzerland---uzbekistan-karimova" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="switzerland---uzbekistan-karimova"><span class="header-section-number">5.1</span> Switzerland -&gt; Uzbekistan (Karimova)</h3>
<section id="essence-of-the-accusation" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="essence-of-the-accusation"><span class="header-section-number">5.1.1</span> Essence of the accusation</h4>
<p>The case concerns <strong>Gulnara Karimova</strong>, daughter of former Uzbek president Islam Karimov. Swiss materials describe the assets as connected to criminal proceedings in Switzerland involving <strong>illicitly acquired assets</strong> and official statements tie the matter to corruption around the award of lucrative telecommunications contracts.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</section>
<section id="parties" class="level4" data-number="5.1.2">
<h4 data-number="5.1.2" class="anchored" data-anchor-id="parties"><span class="header-section-number">5.1.2</span> Parties</h4>
<ul>
<li><strong>Confiscating state:</strong> Switzerland</li>
<li><strong>Receiving state:</strong> Uzbekistan</li>
<li><strong>Implementation vehicle:</strong> UN Multi-Partner Trust Fund</li>
<li><strong>Beneficiary:</strong> population of Uzbekistan</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions" class="level4" data-number="5.1.3">
<h4 data-number="5.1.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions"><span class="header-section-number">5.1.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>Switzerland definitively confiscated an initial tranche of around <strong>USD 131 million</strong> in one of the Swiss criminal proceedings.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></li>
<li>On <strong>11 September 2020</strong>, Switzerland and Uzbekistan signed a <strong>framework agreement</strong> setting the principles and stages for restitution.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></li>
<li>On <strong>16 August 2022</strong>, they signed the legally binding <strong>restitution agreement</strong> after negotiations over governance and implementation.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></li>
<li>The assets were to be returned through a new <strong>UN Multi-Partner Trust Fund</strong>, not as a direct transfer into the Uzbek state budget.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.5" data-fig-height="5.2" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 42, 'nodeSpacing': 32}}}%%
flowchart TD
    subgraph SW["Confiscation and agreements"]
        S1["Swiss criminal proceedings:&lt;br/&gt;illicit assets tied to Karimova / telecom corruption"]
        S2["Definitive confiscation&lt;br/&gt;initial tranche ~USD 131M discussed in 2020 framework"]
        S3["11 Sep 2020 framework agreement&lt;br/&gt;principles and stages non-binding"]
        S4["16 Aug 2022 binding restitution agreement&lt;br/&gt;UN trust fund as destination"]
        S1 --&gt; S2 --&gt; S3 --&gt; S4
    end
    subgraph UN["Implementation vehicle"]
        U1["UN Multi-Partner Trust Fund&lt;br/&gt;Uzbekistan Vision 2030 Fund"]
        U2["Management Committee:&lt;br/&gt;Switzerland, Uzbekistan, UN"]
        U3["UN agencies implement projects&lt;br/&gt;health, education, SDG alignment"]
        U4["CSO consultative body&lt;br/&gt;monitoring and transparency"]
        U1 --&gt; U2 --&gt; U3
        U2 --&gt; U4
    end
    S4 --&gt; U1
</pre>
</div>
<p></p><figcaption> Switzerland–Uzbekistan: confiscation, agreements, and UN trust-fund delivery</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return" class="level4" data-number="5.1.4">
<h4 data-number="5.1.4" class="anchored" data-anchor-id="basis-for-return"><span class="header-section-number">5.1.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Confiscation</td>
<td>Definitive confiscation in Swiss criminal proceedings</td>
</tr>
<tr class="even">
<td>Transfer abroad</td>
<td>2020 framework agreement followed by 2022 restitution agreement</td>
</tr>
<tr class="odd">
<td>Restrictions on use</td>
<td>UN trust-fund architecture; SDG-oriented public-benefit projects; governance rules and consultative role for civil society</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects" class="level4" data-number="5.1.5">
<h4 data-number="5.1.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects"><span class="header-section-number">5.1.5</span> Use of returned assets / joint projects</h4>
<p>Swiss and UN materials show the funds were designed to support the population of Uzbekistan through projects aligned with the UN Sustainable Development Cooperation Framework. Swiss follow-up reporting links the mechanism to <strong>health-sector implementation</strong>, including upgrades to maternity and neonatal care units and training of healthcare workers.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a><a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a><a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
</section>
<section id="why-it-matters-for-ukraine" class="level4" data-number="5.1.6">
<h4 data-number="5.1.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine"><span class="header-section-number">5.1.6</span> Why it matters for Ukraine</h4>
<p>This is one of the strongest current models for Ukraine because it shows how a confiscating state can avoid the objection that funds should not be wired directly into a politically sensitive treasury account. The assets are instead routed through a <strong>neutral international vehicle</strong>, with joint governance and public-benefit restrictions.</p>
</section>
<section id="verification-note" class="level4" data-number="5.1.7">
<h4 data-number="5.1.7" class="anchored" data-anchor-id="verification-note"><span class="header-section-number">5.1.7</span> Verification note</h4>
<ul>
<li>Transfer mechanism verified: Yes</li>
<li>Restitution agreement verified: Yes</li>
<li>Use-of-funds track verified: Yes</li>
<li><strong>Later amounts:</strong> after the 2020 framework (~USD 131 million initially identified), Swiss official reporting through 2025 described <strong>larger cumulative confiscated totals</strong> being restituted through the same UN fund architecture.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></li>
<li>Judicial source gap: public Swiss court texts are less visible than the executive restitution materials</li>
</ul>
</section>
<section id="sources" class="level4" data-number="5.1.8">
<h4 data-number="5.1.8" class="anchored" data-anchor-id="sources"><span class="header-section-number">5.1.8</span> Sources</h4>
<ul>
<li>Swiss Federal Council media, framework agreement, 11 Sep 2020<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></li>
<li>Swiss Federal Council media, restitution agreement, 16 Aug 2022<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></li>
<li>UN Multi-Partner Trust Fund for Uzbekistan<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></li>
<li>Swiss FDFA, health-project follow-up and maternity-project reporting (2025)<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></li>
<li>Swiss Federal Council news, Karimova restitution progress and fund use (2025)<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></li>
</ul>
</section>
</section>
<section id="u.s.-jersey---nigeria-abacha-2020-tranche" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="u.s.-jersey---nigeria-abacha-2020-tranche"><span class="header-section-number">5.2</span> U.S. / Jersey -&gt; Nigeria (Abacha, 2020 tranche)</h3>
<section id="essence-of-the-accusation-1" class="level4" data-number="5.2.1">
<h4 data-number="5.2.1" class="anchored" data-anchor-id="essence-of-the-accusation-1"><span class="header-section-number">5.2.1</span> Essence of the accusation</h4>
<p>The U.S. and Jersey materials treat the funds as proceeds of the kleptocracy of <strong>General Sani Abacha</strong> and his co-conspirators. The allegations included <strong>embezzlement, misappropriation, extortion, and laundering</strong> of billions from Nigeria through the international financial system.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a><a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
</section>
<section id="parties-1" class="level4" data-number="5.2.2">
<h4 data-number="5.2.2" class="anchored" data-anchor-id="parties-1"><span class="header-section-number">5.2.2</span> Parties</h4>
<ul>
<li><strong>Forfeiting state:</strong> United States</li>
<li><strong>Enforcing jurisdiction for located assets:</strong> Jersey</li>
<li><strong>Recipient:</strong> Federal Republic of Nigeria</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-1" class="level4" data-number="5.2.3">
<h4 data-number="5.2.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-1"><span class="header-section-number">5.2.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>In <strong>2014</strong>, Judge John D. Bates in the U.S. District Court for the District of Columbia entered judgment forfeiting roughly <strong>USD 480 million</strong> in assets tied to the case (DOJ described on the order of half a billion dollars in related accounts worldwide).<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></li>
<li>After U.S. appeals were exhausted in <strong>2018</strong>, Jersey enforced the U.S. judgment against more than <strong>USD 308 million</strong> located there.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></li>
<li>On <strong>3 February 2020</strong>, the U.S., Nigeria, and Jersey executed a <strong>trilateral repatriation agreement</strong>.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></li>
<li>On <strong>4 May 2020</strong>, DOJ announced transfer of <strong>USD 311,797,876.11</strong> to Nigeria pursuant to that agreement.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.4" data-fig-height="4.8" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 38, 'nodeSpacing': 30}}}%%
flowchart TD
    A["2014 U.S. D.D.C. civil forfeiture judgment&lt;br/&gt;Judge Bates Abacha kleptocracy proceeds"]
    B["Appeals exhausted 2018"]
    C["Jersey: recognition / enforcement track&lt;br/&gt;over USD 308M located"]
    D["3 Feb 2020 trilateral agreement&lt;br/&gt;U.S., Jersey, Nigeria"]
    E["4 May 2020 transfer&lt;br/&gt;approx. USD 311.8M to Nigeria"]
    F["Safeguards in agreement&lt;br/&gt;transparency and accountability conditions"]
    A --&gt; B --&gt; C --&gt; D --&gt; E
    D -.-&gt; F
    E -.-&gt; F
</pre>
</div>
<p></p><figcaption> Abacha proceeds: U.S. judgment, Jersey enforcement, and 2020 trilateral repatriation</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-1" class="level4" data-number="5.2.4">
<h4 data-number="5.2.4" class="anchored" data-anchor-id="basis-for-return-1"><span class="header-section-number">5.2.4</span> Basis for return</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forfeiture</td>
<td>2014 U.S. civil forfeiture judgment</td>
</tr>
<tr class="even">
<td>Cross-border enforcement</td>
<td>Jersey enforcement of the U.S. judgment</td>
</tr>
<tr class="odd">
<td>Transfer abroad</td>
<td>2020 trilateral repatriation agreement</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-1" class="level4" data-number="5.2.5">
<h4 data-number="5.2.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-1"><span class="header-section-number">5.2.5</span> Use of returned assets / joint projects</h4>
<p>DOJ’s 2020 transfer release confirms the transfer followed the trilateral agreement and emphasizes the presence of <strong>lawful process</strong> and <strong>transparency and accountability safeguards</strong>.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a><a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a> The case is especially useful when read together with later Abacha repatriation agreements, which made the infrastructure uses and monitoring architecture more explicit.</p>
</section>
<section id="why-it-matters-for-ukraine-1" class="level4" data-number="5.2.6">
<h4 data-number="5.2.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-1"><span class="header-section-number">5.2.6</span> Why it matters for Ukraine</h4>
<p>The practical lesson is not just “money was returned.” It is that <strong>one state’s forfeiture judgment can be enforced in another allied jurisdiction and then repatriated through a structured agreement</strong>. That is directly relevant if Ukrainian-benefit assets are scattered across multiple partner states.</p>
</section>
<section id="verification-note-1" class="level4" data-number="5.2.7">
<h4 data-number="5.2.7" class="anchored" data-anchor-id="verification-note-1"><span class="header-section-number">5.2.7</span> Verification note</h4>
<ul>
<li>Forfeiture judgment basis verified: Yes</li>
<li>Trilateral return instrument verified: Yes</li>
<li>Exact project-level use in this tranche: less explicit in the DOJ summary than in later Nigeria return agreements</li>
</ul>
</section>
<section id="sources-1" class="level4" data-number="5.2.8">
<h4 data-number="5.2.8" class="anchored" data-anchor-id="sources-1"><span class="header-section-number">5.2.8</span> Sources</h4>
<ul>
<li>DOJ trilateral agreement, 3 Feb 2020<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></li>
<li>DOJ transfer announcement, 4 May 2020<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a></li>
</ul>
</section>
</section>
<section id="u.s.-uk---nigeria-abacha-2022-tranche" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="u.s.-uk---nigeria-abacha-2022-tranche"><span class="header-section-number">5.3</span> U.S. / UK -&gt; Nigeria (Abacha, 2022 tranche)</h3>
<section id="essence-of-the-accusation-2" class="level4" data-number="5.3.1">
<h4 data-number="5.3.1" class="anchored" data-anchor-id="essence-of-the-accusation-2"><span class="header-section-number">5.3.1</span> Essence of the accusation</h4>
<p>This is a second Abacha repatriation track involving the same larger kleptocracy allegations, but with additional assets located in the <strong>United Kingdom</strong> and recovered through cooperation in restraint and enforcement.<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a><a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a></p>
</section>
<section id="parties-2" class="level4" data-number="5.3.2">
<h4 data-number="5.3.2" class="anchored" data-anchor-id="parties-2"><span class="header-section-number">5.3.2</span> Parties</h4>
<ul>
<li><strong>Forfeiting state:</strong> United States</li>
<li><strong>Supporting enforcement jurisdiction:</strong> United Kingdom</li>
<li><strong>Recipient:</strong> Federal Republic of Nigeria</li>
<li><strong>Project administrator:</strong> Nigeria Sovereign Investment Authority (NSIA)</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-2" class="level4" data-number="5.3.3">
<h4 data-number="5.3.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-2"><span class="header-section-number">5.3.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>DOJ relied on the same <strong>2014 D.D.C. forfeiture judgment</strong> that had already produced the 2020 Jersey tranche.<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a></li>
<li>The UK enforced the U.S. judgment against additional assets and cooperated in investigation and restraint.<a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a></li>
<li>On <strong>23 August 2022</strong>, the U.S. and Nigeria signed an agreement to repatriate over <strong>USD 23 million</strong>.<a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a></li>
<li>On <strong>17 November 2022</strong>, DOJ announced the transfer of over <strong>USD 20.6 million</strong> in accordance with that agreement.<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.4" data-fig-height="4.5" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 36, 'nodeSpacing': 28}}}%%
flowchart TD
    A["Same 2014 U.S. forfeiture judgment line"]
    B["UK: cooperation restraint / enforcement&lt;br/&gt;on additional Abacha-linked assets"]
    C["23 Aug 2022 U.S.-Nigeria agreement&lt;br/&gt;approx. USD 23M framework"]
    D["17 Nov 2022 transfer&lt;br/&gt;approx. USD 20.6M"]
    E["Nigeria Sovereign Investment Authority"]
    F["Earmarked projects:&lt;br/&gt;Second Niger Bridge, Lagos-Ibadan Expressway, Abuja-Kano road"]
    G["Independent auditor + civil society monitor&lt;br/&gt;use restrictions in agreement"]
    A --&gt; B --&gt; C --&gt; D --&gt; E --&gt; F
    E -.-&gt; G
    F -.-&gt; G
</pre>
</div>
<p></p><figcaption> Abacha 2022 tranche: UK-linked assets, bilateral U.S.–Nigeria agreement, NSIA project delivery</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-2" class="level4" data-number="5.3.4">
<h4 data-number="5.3.4" class="anchored" data-anchor-id="basis-for-return-2"><span class="header-section-number">5.3.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forfeiture</td>
<td>2014 U.S. civil forfeiture judgment</td>
</tr>
<tr class="even">
<td>Cross-border enforcement</td>
<td>UK enforcement of U.S. judgment against assets located in the UK</td>
</tr>
<tr class="odd">
<td>Transfer abroad</td>
<td>2022 U.S.-Nigeria repatriation agreement</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-2" class="level4" data-number="5.3.5">
<h4 data-number="5.3.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-2"><span class="header-section-number">5.3.5</span> Use of returned assets / joint projects</h4>
<p>The agreement directed the funds to three already authorized public infrastructure projects: the <strong>Second Niger Bridge</strong>, <strong>Lagos-Ibadan Expressway</strong>, and <strong>Abuja-Kano road</strong>. DOJ expressly noted administration by <strong>NSIA</strong>, review by an <strong>independent auditor</strong>, monitoring by an <strong>independent civil society organization</strong>, and a bar on use to benefit alleged perpetrators or pay contingency-fee lawyers.<a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a></p>
</section>
<section id="why-it-matters-for-ukraine-2" class="level4" data-number="5.3.6">
<h4 data-number="5.3.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-2"><span class="header-section-number">5.3.6</span> Why it matters for Ukraine</h4>
<p>This is a strong case for a Ukraine model because it shows how partner governments can convert a general “return the money” decision into a <strong>project-specific public-benefit arrangement</strong> with named projects, institutional administration, audit, and exclusions.</p>
</section>
<section id="verification-note-2" class="level4" data-number="5.3.7">
<h4 data-number="5.3.7" class="anchored" data-anchor-id="verification-note-2"><span class="header-section-number">5.3.7</span> Verification note</h4>
<ul>
<li>Agreement verified: Yes</li>
<li>Transfer verified: Yes</li>
<li>Use-of-funds restrictions verified: Yes</li>
</ul>
</section>
<section id="sources-2" class="level4" data-number="5.3.8">
<h4 data-number="5.3.8" class="anchored" data-anchor-id="sources-2"><span class="header-section-number">5.3.8</span> Sources</h4>
<ul>
<li>DOJ agreement, 23 Aug 2022<a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a></li>
<li>DOJ transfer, 17 Nov 2022<a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a></li>
</ul>
</section>
</section>
<section id="u.s.---nigeria-alison-madueke-aluko-omokore" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="u.s.---nigeria-alison-madueke-aluko-omokore"><span class="header-section-number">5.4</span> U.S. -&gt; Nigeria (Alison-Madueke / Aluko-Omokore)</h3>
<section id="essence-of-the-accusation-3" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="essence-of-the-accusation-3"><span class="header-section-number">5.4.1</span> Essence of the accusation</h4>
<p>According to DOJ, Nigerian businessmen <strong>Kolawole Aluko</strong> and <strong>Olajide Omokore</strong> conspired with others to pay bribes to former Nigerian Minister for Petroleum Resources <strong>Diezani Alison-Madueke</strong> from <strong>2011 to 2015</strong>. In return, Alison-Madueke allegedly steered lucrative oil contracts to companies linked to them. DOJ states that more than <strong>USD 100 million</strong> in proceeds was laundered into and through the United States and used to purchase luxury real estate and the yacht <strong>Galactica Star</strong>.<a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a></p>
</section>
<section id="parties-3" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="parties-3"><span class="header-section-number">5.4.2</span> Parties</h4>
<ul>
<li><strong>Forfeiting state:</strong> United States</li>
<li><strong>Recipient state:</strong> Nigeria</li>
<li><strong>Implementation vehicles:</strong> World Bank trust fund and International Institute for Justice and the Rule of Law (IIJ)</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-3" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-3"><span class="header-section-number">5.4.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>U.S. authorities pursued forfeiture of assets tied to corruption, bribery, and money laundering involving the Nigerian oil sector.<a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a></li>
<li>Nigeria provided significant evidentiary and investigative assistance to the United States.<a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a></li>
<li>On <strong>10 January 2025</strong>, the U.S. entered into an agreement with Nigeria to transfer approximately <strong>USD 52.88 million</strong> in forfeited proceeds.<a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.2" data-fig-height="4.2" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 34, 'nodeSpacing': 26}}}%%
flowchart TD
    A["U.S. forfeiture pipeline&lt;br/&gt;Alison-Madueke / Aluko-Omokore oil-sector bribery and laundering"]
    B["10 Jan 2025 bilateral transfer agreement&lt;br/&gt;USD 52.88M total"]
    C["approx. USD 50M: Distributed Access Through Renewable Energy Scale-Up"]
    D["World Bank trust fund +&lt;br/&gt;Rural Electrification Agency"]
    E["approx. USD 2.88M: International Institute for Justice and the Rule of Law IIJ"]
    F["Oversight: WB controls, auditing,&lt;br/&gt;reporting, periodic public updates"]
    A --&gt; B
    B --&gt; C --&gt; D
    B --&gt; E
    C -.-&gt; F
    D -.-&gt; F
</pre>
</div>
<p></p><figcaption> 2025 U.S.–Nigeria transfer: split-beneficiary architecture (recovery + rule-of-law channel)</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-3" class="level4" data-number="5.4.4">
<h4 data-number="5.4.4" class="anchored" data-anchor-id="basis-for-return-3"><span class="header-section-number">5.4.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forfeiture</td>
<td>U.S. forfeiture proceedings arising from corruption and laundering</td>
</tr>
<tr class="even">
<td>Transfer abroad</td>
<td>2025 U.S.-Nigeria transfer agreement</td>
</tr>
<tr class="odd">
<td>Authority to share</td>
<td>DOJ notes Attorney General may share successful forfeiture proceeds with foreign countries that participated in seizure or forfeiture, in coordination with Treasury and State</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-3" class="level4" data-number="5.4.5">
<h4 data-number="5.4.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-3"><span class="header-section-number">5.4.5</span> Use of returned assets / joint projects</h4>
<p>The agreement is unusually useful because it split the funds into <strong>two distinct public-benefit tracks</strong>:</p>
<ul>
<li><strong>USD 50 million</strong> for the <strong>Distributed Access Through Renewable Energy Scale-Up project</strong>, through a <strong>World Bank trust fund</strong> and Rural Electrification Agency implementation;</li>
<li>about <strong>USD 2.88 million</strong> for Nigeria’s contribution to the <strong>International Institute for Justice and the Rule of Law</strong>, supporting regional criminal-justice and counter-terrorism capacity-building.<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a></li>
</ul>
<p>The agreement also included <strong>World Bank oversight controls, auditing, publication requirements, periodic progress reporting, and public reporting</strong>.<a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a></p>
</section>
<section id="why-it-matters-for-ukraine-3" class="level4" data-number="5.4.6">
<h4 data-number="5.4.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-3"><span class="header-section-number">5.4.6</span> Why it matters for Ukraine</h4>
<p>This is one of the best current analogues for Ukraine because it demonstrates a <strong>split-beneficiary architecture</strong>: part of the return can go to infrastructure or recovery spending and part can reinforce rule-of-law or security institutions. That is closer to Ukraine’s likely needs than a single unrestricted transfer.</p>
</section>
<section id="verification-note-3" class="level4" data-number="5.4.7">
<h4 data-number="5.4.7" class="anchored" data-anchor-id="verification-note-3"><span class="header-section-number">5.4.7</span> Verification note</h4>
<ul>
<li>Agreement verified: Yes</li>
<li>End-use and oversight details verified: Yes</li>
<li>Judicial source gap: underlying forfeiture filings should still be added in a later annex</li>
</ul>
</section>
<section id="sources-3" class="level4" data-number="5.4.8">
<h4 data-number="5.4.8" class="anchored" data-anchor-id="sources-3"><span class="header-section-number">5.4.8</span> Sources</h4>
<ul>
<li>DOJ agreement, 10 Jan 2025<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a></li>
</ul>
</section>
</section>
<section id="jersey---kenya-windward-gichuru-okemo" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="jersey---kenya-windward-gichuru-okemo"><span class="header-section-number">5.5</span> Jersey -&gt; Kenya (Windward / Gichuru-Okemo)</h3>
<section id="essence-of-the-accusation-4" class="level4" data-number="5.5.1">
<h4 data-number="5.5.1" class="anchored" data-anchor-id="essence-of-the-accusation-4"><span class="header-section-number">5.5.1</span> Essence of the accusation</h4>
<p>The Jersey proceedings concerned <strong>Windward Trading Limited</strong>, whose beneficial owner was <strong>Samuel Gichuru</strong>, then chief executive of Kenya Power and Lighting Company. Jersey states the company admitted laundering proceeds of corruption linked to valuable Kenyan contracts, with the case also involving former Kenyan Energy Minister <strong>Chrysanthus Okemo</strong> in connected extradition efforts.<a href="#fn44" class="footnote-ref" id="fnref44" role="doc-noteref"><sup>44</sup></a><a href="#fn45" class="footnote-ref" id="fnref45" role="doc-noteref"><sup>45</sup></a><a href="#fn46" class="footnote-ref" id="fnref46" role="doc-noteref"><sup>46</sup></a></p>
</section>
<section id="parties-4" class="level4" data-number="5.5.2">
<h4 data-number="5.5.2" class="anchored" data-anchor-id="parties-4"><span class="header-section-number">5.5.2</span> Parties</h4>
<ul>
<li><strong>Confiscating jurisdiction:</strong> Jersey</li>
<li><strong>Recipient:</strong> Kenya</li>
<li><strong>Framework partners:</strong> Jersey, Kenya, United Kingdom, Switzerland under FRACCK</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-4" class="level4" data-number="5.5.3">
<h4 data-number="5.5.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-4"><span class="header-section-number">5.5.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>On <strong>24 February 2016</strong>, Windward pleaded guilty before the Royal Court of Jersey and the court imposed a confiscation order of <strong>GBP 3,281,897.40 and USD 540,330.69</strong>.<a href="#fn47" class="footnote-ref" id="fnref47" role="doc-noteref"><sup>47</sup></a></li>
<li>On <strong>3 March 2017</strong>, Jersey and Kenya signed an agreement paving the way for return of over <strong>GBP 3 million</strong>.<a href="#fn48" class="footnote-ref" id="fnref48" role="doc-noteref"><sup>48</sup></a></li>
<li>In <strong>December 2018</strong>, Jersey signed the <strong>Framework for Return of Assets from Corruption and Crime to Kenya (FRACCK)</strong>, a multilateral framework also involving the UK and Switzerland.<a href="#fn49" class="footnote-ref" id="fnref49" role="doc-noteref"><sup>49</sup></a></li>
<li>On <strong>28 March 2022</strong>, Jersey and Kenya signed an <strong>Asset Recovery Agreement</strong> enabling the first return under FRACCK, with <strong>GBP 3 million</strong> to support Kenya’s response to COVID-19.<a href="#fn50" class="footnote-ref" id="fnref50" role="doc-noteref"><sup>50</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.4" data-fig-height="4.8" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 38, 'nodeSpacing': 30}}}%%
flowchart TD
    W1["24 Feb 2016 Windward guilty plea&lt;br/&gt;Royal Court confiscation order"]
    W2["3 Mar 2017 Jersey-Kenya agreement&lt;br/&gt;path to return over GBP 3M"]
    W3["Dec 2018 FRACCK signed&lt;br/&gt;Jersey, Kenya, UK, Switzerland"]
    W4["28 Mar 2022 Asset Recovery Agreement&lt;br/&gt;first disbursement under FRACCK"]
    W5["Use: COVID-19 response and&lt;br/&gt;Vision 2030 development objectives"]
    W1 --&gt; W2 --&gt; W3 --&gt; W4 --&gt; W5
</pre>
</div>
<p></p><figcaption> Windward / Kenya: confiscation, bilateral steps, FRACCK framework, and first return</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-4" class="level4" data-number="5.5.4">
<h4 data-number="5.5.4" class="anchored" data-anchor-id="basis-for-return-4"><span class="header-section-number">5.5.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Confiscation</td>
<td>Royal Court confiscation order after criminal conviction</td>
</tr>
<tr class="even">
<td>Transfer abroad</td>
<td>2017 bilateral return step; FRACCK framework; 2022 Asset Recovery Agreement</td>
</tr>
<tr class="odd">
<td>Restrictions on use</td>
<td>Development and public-benefit objectives under FRACCK; Kenya-defined projects agreed with partners</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-4" class="level4" data-number="5.5.5">
<h4 data-number="5.5.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-4"><span class="header-section-number">5.5.5</span> Use of returned assets / joint projects</h4>
<p>The 2022 Jersey statement says the return would support Kenya’s <strong>COVID-19 response</strong>, while the FRACCK framework required returned assets to be used for <strong>clearly identified development objectives</strong> that benefit the Kenyan people and support <strong>Vision 2030</strong>.<a href="#fn51" class="footnote-ref" id="fnref51" role="doc-noteref"><sup>51</sup></a><a href="#fn52" class="footnote-ref" id="fnref52" role="doc-noteref"><sup>52</sup></a></p>
</section>
<section id="why-it-matters-for-ukraine-4" class="level4" data-number="5.5.6">
<h4 data-number="5.5.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-4"><span class="header-section-number">5.5.6</span> Why it matters for Ukraine</h4>
<p>This is important because it shows how a return framework can exist <strong>before</strong> a particular transfer is finalized. For Ukraine, a standing framework among partner states could reduce the need to renegotiate principles in each case.</p>
</section>
<section id="verification-note-4" class="level4" data-number="5.5.7">
<h4 data-number="5.5.7" class="anchored" data-anchor-id="verification-note-4"><span class="header-section-number">5.5.7</span> Verification note</h4>
<ul>
<li>Confiscation verified: Yes</li>
<li>Framework agreement verified: Yes</li>
<li>First return under framework verified: Yes</li>
</ul>
</section>
<section id="sources-4" class="level4" data-number="5.5.8">
<h4 data-number="5.5.8" class="anchored" data-anchor-id="sources-4"><span class="header-section-number">5.5.8</span> Sources</h4>
<ul>
<li>Jersey confiscation (Royal Court 24 Feb 2016; announcement 25 Feb 2016)<a href="#fn53" class="footnote-ref" id="fnref53" role="doc-noteref"><sup>53</sup></a></li>
<li>Jersey-Kenya agreement (signed 3 Mar 2017; announcement 6 Mar 2017)<a href="#fn54" class="footnote-ref" id="fnref54" role="doc-noteref"><sup>54</sup></a></li>
<li>FRACCK / Kenya funds, 12 Dec 2018<a href="#fn55" class="footnote-ref" id="fnref55" role="doc-noteref"><sup>55</sup></a></li>
<li>Asset Recovery Agreement, 28 Mar 2022<a href="#fn56" class="footnote-ref" id="fnref56" role="doc-noteref"><sup>56</sup></a></li>
</ul>
</section>
</section>
<section id="jersey---mozambique-fragoso" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="jersey---mozambique-fragoso"><span class="header-section-number">5.6</span> Jersey -&gt; Mozambique (Fragoso)</h3>
<section id="essence-of-the-accusation-5" class="level4" data-number="5.6.1">
<h4 data-number="5.6.1" class="anchored" data-anchor-id="essence-of-the-accusation-5"><span class="header-section-number">5.6.1</span> Essence of the accusation</h4>
<p>Jersey’s 2024 statement explains that the returned funds were linked to <strong>Carlos Fragoso</strong>, a Mozambican official who had held senior roads and bridge positions. The funds were held in a Jersey trust and treated as tainted property derived from <strong>bribes paid to secure construction contracts in Mozambique</strong>.<a href="#fn57" class="footnote-ref" id="fnref57" role="doc-noteref"><sup>57</sup></a></p>
</section>
<section id="parties-5" class="level4" data-number="5.6.2">
<h4 data-number="5.6.2" class="anchored" data-anchor-id="parties-5"><span class="header-section-number">5.6.2</span> Parties</h4>
<ul>
<li><strong>Confiscating jurisdiction:</strong> Jersey</li>
<li><strong>Recipient:</strong> Republic of Mozambique</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-5" class="level4" data-number="5.6.3">
<h4 data-number="5.6.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-5"><span class="header-section-number">5.6.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>Jersey had previously litigated related trust issues and identified earlier deceptive source-of-income representations.<a href="#fn58" class="footnote-ref" id="fnref58" role="doc-noteref"><sup>58</sup></a></li>
<li>Following cooperation from Mozambican authorities, Jersey’s Economic Crime and Confiscation Unit used the <strong>Forfeiture of Assets (Civil Proceedings) (Jersey) Law 2018</strong> to obtain forfeiture of funds held in the Tolvex Trust.<a href="#fn59" class="footnote-ref" id="fnref59" role="doc-noteref"><sup>59</sup></a></li>
<li>On <strong>7 May 2024</strong>, Jersey and Mozambique signed a <strong>Memorandum of Understanding</strong> returning over <strong>GBP 829,500</strong>.<a href="#fn60" class="footnote-ref" id="fnref60" role="doc-noteref"><sup>60</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.2" data-fig-height="3.6" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 32, 'nodeSpacing': 26}}}%%
flowchart TD
    M1["Tolvex Trust funds linked to Fragoso&lt;br/&gt;bribes on construction contracts"]
    M2["Forfeiture under Jersey&lt;br/&gt;Forfeiture of Assets Civil Proceedings Law 2018"]
    M3["7 May 2024 MoU Jersey-Mozambique"]
    M4["Earmarked uses: asset recovery, anti-corruption,&lt;br/&gt;investigation services, training"]
    M1 --&gt; M2 --&gt; M3 --&gt; M4
</pre>
</div>
<p></p><figcaption> Jersey civil forfeiture (2018 law) and MoU repatriation to Mozambican enforcement institutions</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-5" class="level4" data-number="5.6.4">
<h4 data-number="5.6.4" class="anchored" data-anchor-id="basis-for-return-5"><span class="header-section-number">5.6.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forfeiture</td>
<td>Jersey civil forfeiture under the 2018 law</td>
</tr>
<tr class="even">
<td>Transfer abroad</td>
<td>2024 Jersey-Mozambique Memorandum of Understanding</td>
</tr>
<tr class="odd">
<td>Restrictions on use</td>
<td>Funds earmarked for financial-crime and asset-recovery institutions and training</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-5" class="level4" data-number="5.6.5">
<h4 data-number="5.6.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-5"><span class="header-section-number">5.6.5</span> Use of returned assets / joint projects</h4>
<p>The MoU earmarked most of the funds to support Mozambique’s <strong>Central Office for Asset Recovery</strong>, <strong>Central Office for Combatting Corruption</strong>, <strong>Asset Management Office</strong>, Attorney General’s Office, and National Criminal Investigation Service. The package also funded a five-day training course on <strong>international and judicial cooperation in criminal matters</strong> for trainees from all eleven provinces.<a href="#fn61" class="footnote-ref" id="fnref61" role="doc-noteref"><sup>61</sup></a></p>
</section>
<section id="why-it-matters-for-ukraine-5" class="level4" data-number="5.6.6">
<h4 data-number="5.6.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-5"><span class="header-section-number">5.6.6</span> Why it matters for Ukraine</h4>
<p>This case is smaller than the others, but it is analytically strong because it treats returned assets as a tool to build <strong>state recovery capacity itself</strong>. That is useful if some Ukraine-bound returns are directed to anti-corruption, asset-management, or prosecutorial capacity rather than only reconstruction projects.</p>
</section>
<section id="verification-note-5" class="level4" data-number="5.6.7">
<h4 data-number="5.6.7" class="anchored" data-anchor-id="verification-note-5"><span class="header-section-number">5.6.7</span> Verification note</h4>
<ul>
<li>Forfeiture basis verified: Yes</li>
<li>Return instrument verified: Yes</li>
<li>End-use detail verified: Yes</li>
</ul>
</section>
<section id="sources-5" class="level4" data-number="5.6.8">
<h4 data-number="5.6.8" class="anchored" data-anchor-id="sources-5"><span class="header-section-number">5.6.8</span> Sources</h4>
<ul>
<li>Jersey-Mozambique asset return arrangement, 7 May 2024<a href="#fn62" class="footnote-ref" id="fnref62" role="doc-noteref"><sup>62</sup></a></li>
</ul>
</section>
</section>
<section id="u.s.---kyrgyz-republic-bakiyev" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="u.s.---kyrgyz-republic-bakiyev"><span class="header-section-number">5.7</span> U.S. -&gt; Kyrgyz Republic (Bakiyev)</h3>
<section id="essence-of-the-accusation-6" class="level4" data-number="5.7.1">
<h4 data-number="5.7.1" class="anchored" data-anchor-id="essence-of-the-accusation-6"><span class="header-section-number">5.7.1</span> Essence of the accusation</h4>
<p>DOJ tied the returned funds to corruption and theft of government funds by the prior regime of <strong>Kurmanbek Bakiyev</strong> and his son <strong>Maxim Bakiyev</strong>. The assets were identified in the United States through a criminal prosecution of <strong>Eugene Gourevitch</strong> for <strong>wire fraud and insider trading</strong>, after which a <strong>USD 6 million forfeiture order</strong> was entered.<a href="#fn63" class="footnote-ref" id="fnref63" role="doc-noteref"><sup>63</sup></a></p>
</section>
<section id="parties-6" class="level4" data-number="5.7.2">
<h4 data-number="5.7.2" class="anchored" data-anchor-id="parties-6"><span class="header-section-number">5.7.2</span> Parties</h4>
<ul>
<li><strong>Forfeiting state:</strong> United States</li>
<li><strong>Recipient:</strong> Government of the Kyrgyz Republic</li>
<li><strong>Claim vehicle:</strong> Petition for remission filed by Kyrgyz authorities</li>
</ul>
</section>
<section id="procedural-path-and-operative-decisions-6" class="level4" data-number="5.7.3">
<h4 data-number="5.7.3" class="anchored" data-anchor-id="procedural-path-and-operative-decisions-6"><span class="header-section-number">5.7.3</span> Procedural path and operative decisions</h4>
<ol type="1">
<li>In the Eastern District of New York prosecution of Eugene Gourevitch, the court entered a <strong>USD 6 million forfeiture order</strong>.<a href="#fn64" class="footnote-ref" id="fnref64" role="doc-noteref"><sup>64</sup></a></li>
<li>The Kyrgyz government filed a <strong>petition for remission</strong> with DOJ MLARS claiming the forfeited funds traced back to monies stolen by Maxim Bakiyev from Kyrgyz state authorities and other banking institutions.<a href="#fn65" class="footnote-ref" id="fnref65" role="doc-noteref"><sup>65</sup></a></li>
<li>DOJ granted the remission petition on <strong>4 October 2018</strong>.<a href="#fn66" class="footnote-ref" id="fnref66" role="doc-noteref"><sup>66</sup></a></li>
<li>On <strong>26 February 2019</strong>, DOJ announced repatriation of approximately <strong>USD 4.6 million</strong> collected so far, with additional efforts to locate the remainder.<a href="#fn67" class="footnote-ref" id="fnref67" role="doc-noteref"><sup>67</sup></a></li>
</ol>
<div class="cell" data-fig-width="5.2" data-fig-height="4.2" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 34, 'nodeSpacing': 28}}}%%
flowchart TD
    K1["EDNY: U.S. prosecution of Gourevitch&lt;br/&gt;wire fraud and insider trading"]
    K2["USD 6M criminal forfeiture order"]
    K3["Kyrgyz government: petition for remission to DOJ MLARS&lt;br/&gt;links funds to Maxim Bakiyev theft"]
    K4["4 Oct 2018 remission granted"]
    K5["26 Feb 2019 repatriation announced&lt;br/&gt;approx. USD 4.6M collected; remainder traced"]
    K6["Public-benefit commitments:&lt;br/&gt;health, water, anti-corruption / court transparency"]
    K1 --&gt; K2 --&gt; K3 --&gt; K4 --&gt; K5 --&gt; K6
</pre>
</div>
<p></p><figcaption> Kyrgyz remission route: foreign-state petition following U.S. criminal forfeiture</figcaption> </figure><p></p>
</div>
</div>
</div>
</section>
<section id="basis-for-return-6" class="level4" data-number="5.7.4">
<h4 data-number="5.7.4" class="anchored" data-anchor-id="basis-for-return-6"><span class="header-section-number">5.7.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forfeiture</td>
<td>U.S. criminal forfeiture order</td>
</tr>
<tr class="even">
<td>Transfer abroad</td>
<td>DOJ remission process following foreign-state petition</td>
</tr>
<tr class="odd">
<td>Restrictions on use</td>
<td>Jointly announced public-benefit uses focused on social and anti-corruption projects</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-6" class="level4" data-number="5.7.5">
<h4 data-number="5.7.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-6"><span class="header-section-number">5.7.5</span> Use of returned assets / joint projects</h4>
<p>DOJ and the Kyrgyz government stated the funds would be used for:</p>
<ul>
<li>healthcare access in rural areas through medical equipment;</li>
<li>water-supply facilities and drinking-water systems;</li>
<li>anti-corruption institutions and transparency of court proceedings.<a href="#fn68" class="footnote-ref" id="fnref68" role="doc-noteref"><sup>68</sup></a></li>
</ul>
</section>
<section id="why-it-matters-for-ukraine-6" class="level4" data-number="5.7.6">
<h4 data-number="5.7.6" class="anchored" data-anchor-id="why-it-matters-for-ukraine-6"><span class="header-section-number">5.7.6</span> Why it matters for Ukraine</h4>
<p>This case is important because it shows a different route from bilateral restitution agreements: a <strong>foreign state petitioning for remission</strong> out of a U.S. forfeiture case. It may not be the central Ukraine model, but it shows another legal mechanism for directing forfeited value back to a harmed state.</p>
</section>
<section id="verification-note-6" class="level4" data-number="5.7.7">
<h4 data-number="5.7.7" class="anchored" data-anchor-id="verification-note-6"><span class="header-section-number">5.7.7</span> Verification note</h4>
<ul>
<li>Forfeiture order basis verified: Yes</li>
<li>Remission decision verified: Yes</li>
<li>Public-benefit commitments verified: Yes</li>
</ul>
</section>
<section id="sources-6" class="level4" data-number="5.7.8">
<h4 data-number="5.7.8" class="anchored" data-anchor-id="sources-6"><span class="header-section-number">5.7.8</span> Sources</h4>
<ul>
<li>DOJ repatriation, 26 Feb 2019<a href="#fn69" class="footnote-ref" id="fnref69" role="doc-noteref"><sup>69</sup></a></li>
</ul>
</section>
</section>
</section>
<section id="preliminary-comparative-lessons-for-ukraine" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="preliminary-comparative-lessons-for-ukraine"><span class="header-section-number">6</span> Preliminary Comparative Lessons For Ukraine</h2>
<section id="confiscation-is-usually-necessary-but-not-sufficient" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="confiscation-is-usually-necessary-but-not-sufficient"><span class="header-section-number">6.1</span> 1. Confiscation is usually necessary but not sufficient</h3>
<p>In almost all useful cases, the judicial forfeiture or confiscation step <strong>did not itself settle destination and use</strong>. A second step was required: a bilateral agreement, a trilateral agreement, a trust-fund instrument, or a remission decision.</p>
</section>
<section id="the-politically-safest-route-is-not-a-simple-treasury-transfer" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="the-politically-safest-route-is-not-a-simple-treasury-transfer"><span class="header-section-number">6.2</span> 2. The politically safest route is not a simple treasury transfer</h3>
<p>The most transferable models for Ukraine are the ones that route funds through:</p>
<ul>
<li>a <strong>UN trust fund</strong>;</li>
<li>a <strong>World Bank trust fund</strong>;</li>
<li>a <strong>state project vehicle with external audit</strong>;</li>
<li>a <strong>framework agreement with predefined safeguards</strong>.</li>
</ul>
<p>That pattern appears in the Uzbekistan, Nigeria-2022, and Nigeria-2025 cases.</p>
</section>
<section id="monitoring-architecture-is-not-cosmetic" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="monitoring-architecture-is-not-cosmetic"><span class="header-section-number">6.3</span> 3. Monitoring architecture is not cosmetic</h3>
<p>Monitoring is often what makes return politically acceptable. The recurring mechanisms are:</p>
<ul>
<li>independent audit;</li>
<li>public reporting;</li>
<li>external implementation controls;</li>
<li>civil-society monitoring;</li>
<li>project earmarking;</li>
<li>prohibition on benefit to perpetrators or related persons.</li>
</ul>
<p>Ukraine-facing work should therefore treat monitoring as part of the legal design, not an afterthought.</p>
</section>
<section id="multi-state-enforcement-matters" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="multi-state-enforcement-matters"><span class="header-section-number">6.4</span> 4. Multi-state enforcement matters</h3>
<p>The Abacha 2020 and 2022 tranches are especially relevant because they show how a forfeiture judgment from one state can be <strong>enforced against assets located in another jurisdiction</strong> and only then transferred onward. That is likely to matter in any serious Ukraine asset-recovery pipeline.</p>
</section>
<section id="a-future-ukraine-model-may-need-more-than-one-destination-channel" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="a-future-ukraine-model-may-need-more-than-one-destination-channel"><span class="header-section-number">6.5</span> 5. A future Ukraine model may need more than one destination channel</h3>
<p>The January 10, 2025 U.S.-Nigeria agreement is particularly instructive because it split the assets between:</p>
<ul>
<li>a recovery-style public project channel; and</li>
<li>a rule-of-law / security-capacity channel.</li>
</ul>
<p>That may be a better template for Ukraine than a one-bucket structure.</p>
</section>
</section>
<section id="tentative-conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="tentative-conclusion"><span class="header-section-number">7</span> Tentative Conclusion</h2>
<p>At this stage, the strongest new cases for a Ukraine-oriented final note are:</p>
<ol type="1">
<li><strong>Switzerland -&gt; Uzbekistan (Karimova)</strong> for the UN trust-fund model;</li>
<li><strong>U.S. -&gt; Nigeria (Alison-Madueke / Aluko-Omokore)</strong> for a split architecture combining infrastructure-type spending and institutional capacity-building;</li>
<li><strong>U.S. / UK -&gt; Nigeria (Abacha, 2022 tranche)</strong> for project-specific safeguards after cross-border enforcement;</li>
<li><strong>Jersey -&gt; Kenya (Windward / FRACCK)</strong> for a standing framework model;</li>
<li><strong>U.S. -&gt; Kyrgyz Republic (Bakiyev)</strong> for the remission route;</li>
<li><strong>Jersey -&gt; Mozambique (Fragoso)</strong> for anti-corruption institution-building as an end use.</li>
</ol>
<p>The emerging lesson is that a plausible Ukraine model will likely require:</p>
<ul>
<li>finalized confiscation in the holding state;</li>
<li>a separate interstate allocation instrument;</li>
<li>a protected beneficiary vehicle;</li>
<li>strong monitoring and public reporting;</li>
<li>and, in some cases, a split between reconstruction uses and institutional rule-of-law uses.</li>
</ul>
</section>
<section id="sources-7" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sources-7"><span class="header-section-number">8</span> Sources</h2>
<p>The analysis above relies on the following official and institutional materials, cited in full below. <strong>Switzerland–Uzbekistan (Karimova):</strong> Swiss Federal Council media on the 2020 framework and 2022 restitution agreements<a href="#fn70" class="footnote-ref" id="fnref70" role="doc-noteref"><sup>70</sup></a><a href="#fn71" class="footnote-ref" id="fnref71" role="doc-noteref"><sup>71</sup></a>; UN Multi-Partner Trust Fund documentation for the Uzbekistan Vision 2030 Fund<a href="#fn72" class="footnote-ref" id="fnref72" role="doc-noteref"><sup>72</sup></a>; Swiss FDFA reporting on maternity-unit upgrades funded from restituted assets<a href="#fn73" class="footnote-ref" id="fnref73" role="doc-noteref"><sup>73</sup></a>; and Swiss Federal Council / FDFA news on the same restitution programme and project inaugurations<a href="#fn74" class="footnote-ref" id="fnref74" role="doc-noteref"><sup>74</sup></a>. <strong>United States–Nigeria (Abacha, Jersey and UK tranches):</strong> DOJ press releases on the 2020 trilateral agreement with Jersey and the transfer announcement<a href="#fn75" class="footnote-ref" id="fnref75" role="doc-noteref"><sup>75</sup></a><a href="#fn76" class="footnote-ref" id="fnref76" role="doc-noteref"><sup>76</sup></a>, and on the 2022 bilateral agreement and subsequent transfer<a href="#fn77" class="footnote-ref" id="fnref77" role="doc-noteref"><sup>77</sup></a><a href="#fn78" class="footnote-ref" id="fnref78" role="doc-noteref"><sup>78</sup></a>. <strong>United States–Nigeria (Alison-Madueke / Aluko-Omokore):</strong> DOJ press release on the January 2025 transfer agreement<a href="#fn79" class="footnote-ref" id="fnref79" role="doc-noteref"><sup>79</sup></a>. <strong>Jersey–Kenya (Windward / FRACCK):</strong> Government of Jersey announcements on the 2016 confiscation<a href="#fn80" class="footnote-ref" id="fnref80" role="doc-noteref"><sup>80</sup></a>, the 2017 agreement with Kenya<a href="#fn81" class="footnote-ref" id="fnref81" role="doc-noteref"><sup>81</sup></a>, FRACCK in 2018<a href="#fn82" class="footnote-ref" id="fnref82" role="doc-noteref"><sup>82</sup></a>, and the 2022 Asset Recovery Agreement<a href="#fn83" class="footnote-ref" id="fnref83" role="doc-noteref"><sup>83</sup></a>. <strong>Jersey–Mozambique (Fragoso):</strong> Government of Jersey statement on the May 2024 return arrangement<a href="#fn84" class="footnote-ref" id="fnref84" role="doc-noteref"><sup>84</sup></a>. <strong>United States–Kyrgyz Republic (Bakiyev remission):</strong> DOJ press release on repatriation following remission<a href="#fn85" class="footnote-ref" id="fnref85" role="doc-noteref"><sup>85</sup></a>.</p>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Swiss Federal Council, “Switzerland and Uzbekistan sign an agreement with a view to the restitution of confiscated assets”, 11 Sep 2020, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Swiss FDFA, “Upgrades to maternity units in Uzbekistan thanks to return of confiscated assets”, 24 Apr 2025, <a href="https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets" class="uri">https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Swiss Federal Council, “Switzerland and Uzbekistan sign an agreement with a view to the restitution of confiscated assets”, 11 Sep 2020, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Swiss Federal Council, “Switzerland and Uzbekistan sign an agreement with a view to the restitution of confiscated assets”, 11 Sep 2020, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>UN Multi-Partner Trust Fund Office, “Uzbekistan Vision 2030 Fund”, accessed 7 Apr 2026, <a href="https://mptf.undp.org/fund/uzb00" class="uri">https://mptf.undp.org/fund/uzb00</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>UN Multi-Partner Trust Fund Office, “Uzbekistan Vision 2030 Fund”, accessed 7 Apr 2026, <a href="https://mptf.undp.org/fund/uzb00" class="uri">https://mptf.undp.org/fund/uzb00</a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Swiss FDFA, “Upgrades to maternity units in Uzbekistan thanks to return of confiscated assets”, 24 Apr 2025, <a href="https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets" class="uri">https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets</a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Swiss Federal Council / FDFA, “Uzbekistan: inauguration of the first maternity units modernised thanks to Karimova assets returned by Switzerland”, 24 Apr 2025, <a href="https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg" class="uri">https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Swiss Federal Council, “Switzerland and Uzbekistan sign an agreement with a view to the restitution of confiscated assets”, 11 Sep 2020, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>UN Multi-Partner Trust Fund Office, “Uzbekistan Vision 2030 Fund”, accessed 7 Apr 2026, <a href="https://mptf.undp.org/fund/uzb00" class="uri">https://mptf.undp.org/fund/uzb00</a>.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Swiss FDFA, “Upgrades to maternity units in Uzbekistan thanks to return of confiscated assets”, 24 Apr 2025, <a href="https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets" class="uri">https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets</a>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Swiss Federal Council / FDFA, “Uzbekistan: inauguration of the first maternity units modernised thanks to Karimova assets returned by Switzerland”, 24 Apr 2025, <a href="https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg" class="uri">https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>U.S. Department of Justice, “U.S. Repatriates over $311.7 Million in Assets to the Nigerian People that were Stolen by Former Nigerian Dictator and His Associates”, 4 May 2020, <a href="https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>U.S. Department of Justice, “U.S. Repatriates over $311.7 Million in Assets to the Nigerian People that were Stolen by Former Nigerian Dictator and His Associates”, 4 May 2020, <a href="https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator</a>.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>U.S. Department of Justice, “U.S. Repatriates over $311.7 Million in Assets to the Nigerian People that were Stolen by Former Nigerian Dictator and His Associates”, 4 May 2020, <a href="https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator</a>.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>U.S. Department of Justice, “U.S. Repatriates over $311.7 Million in Assets to the Nigerian People that were Stolen by Former Nigerian Dictator and His Associates”, 4 May 2020, <a href="https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator</a>.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p>U.S. Department of Justice, “United States Repatriates Over $20 Million in Assets Stolen by Former Nigerian Dictator”, 17 Nov 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator</a>.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p>U.S. Department of Justice, “United States Repatriates Over $20 Million in Assets Stolen by Former Nigerian Dictator”, 17 Nov 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator</a>.<a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p>U.S. Department of Justice, “United States Repatriates Over $20 Million in Assets Stolen by Former Nigerian Dictator”, 17 Nov 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator</a>.<a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn44"><p>Government of Jersey, “Jersey confiscates £3.6 million proceeds of corruption” (Royal Court 24 Feb 2016; announcement 25 Feb 2016), <a href="https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx" class="uri">https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx</a>.<a href="#fnref44" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn45"><p>Government of Jersey, “Chief Minister signs agreement with Kenya” (signed 3 Mar 2017; announcement 6 Mar 2017), <a href="https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx" class="uri">https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx</a>.<a href="#fnref45" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn46"><p>Government of Jersey, “Jersey and Kenya sign historic Asset Recovery Agreement”, 28 Mar 2022, <a href="https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx" class="uri">https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx</a>.<a href="#fnref46" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn47"><p>Government of Jersey, “Jersey confiscates £3.6 million proceeds of corruption” (Royal Court 24 Feb 2016; announcement 25 Feb 2016), <a href="https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx" class="uri">https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx</a>.<a href="#fnref47" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn48"><p>Government of Jersey, “Chief Minister signs agreement with Kenya” (signed 3 Mar 2017; announcement 6 Mar 2017), <a href="https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx" class="uri">https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx</a>.<a href="#fnref48" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn49"><p>Government of Jersey, “Confiscated funds to return to Kenya”, 12 Dec 2018, <a href="https://www.gov.je/news/2018/pages/kenyafunds.aspx" class="uri">https://www.gov.je/news/2018/pages/kenyafunds.aspx</a>.<a href="#fnref49" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn50"><p>Government of Jersey, “Jersey and Kenya sign historic Asset Recovery Agreement”, 28 Mar 2022, <a href="https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx" class="uri">https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx</a>.<a href="#fnref50" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn51"><p>Government of Jersey, “Confiscated funds to return to Kenya”, 12 Dec 2018, <a href="https://www.gov.je/news/2018/pages/kenyafunds.aspx" class="uri">https://www.gov.je/news/2018/pages/kenyafunds.aspx</a>.<a href="#fnref51" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn52"><p>Government of Jersey, “Jersey and Kenya sign historic Asset Recovery Agreement”, 28 Mar 2022, <a href="https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx" class="uri">https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx</a>.<a href="#fnref52" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn53"><p>Government of Jersey, “Jersey confiscates £3.6 million proceeds of corruption” (Royal Court 24 Feb 2016; announcement 25 Feb 2016), <a href="https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx" class="uri">https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx</a>.<a href="#fnref53" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn54"><p>Government of Jersey, “Chief Minister signs agreement with Kenya” (signed 3 Mar 2017; announcement 6 Mar 2017), <a href="https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx" class="uri">https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx</a>.<a href="#fnref54" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn55"><p>Government of Jersey, “Confiscated funds to return to Kenya”, 12 Dec 2018, <a href="https://www.gov.je/news/2018/pages/kenyafunds.aspx" class="uri">https://www.gov.je/news/2018/pages/kenyafunds.aspx</a>.<a href="#fnref55" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn56"><p>Government of Jersey, “Jersey and Kenya sign historic Asset Recovery Agreement”, 28 Mar 2022, <a href="https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx" class="uri">https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx</a>.<a href="#fnref56" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn57"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref57" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn58"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref58" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn59"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref59" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn60"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref60" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn61"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref61" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn62"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref62" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn63"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref63" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn64"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref64" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn65"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref65" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn66"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref66" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn67"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref67" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn68"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref68" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn69"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref69" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn70"><p>Swiss Federal Council, “Switzerland and Uzbekistan sign an agreement with a view to the restitution of confiscated assets”, 11 Sep 2020, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-80393.html</a>.<a href="#fnref70" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn71"><p>Swiss Federal Council, “Restitution of illicit assets: Switzerland and Uzbekistan sign agreement”, 16 Aug 2022, <a href="https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html" class="uri">https://www.admin.ch/gov/en/start/documentation/media-releases.msg-id-89949.html</a>.<a href="#fnref71" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn72"><p>UN Multi-Partner Trust Fund Office, “Uzbekistan Vision 2030 Fund”, accessed 7 Apr 2026, <a href="https://mptf.undp.org/fund/uzb00" class="uri">https://mptf.undp.org/fund/uzb00</a>.<a href="#fnref72" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn73"><p>Swiss FDFA, “Upgrades to maternity units in Uzbekistan thanks to return of confiscated assets”, 24 Apr 2025, <a href="https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets" class="uri">https://www.eda.admin.ch/en/upgrades-to-maternity-units-in-uzbekistan-thanks-to-return-of-confiscated-assets</a>.<a href="#fnref73" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn74"><p>Swiss Federal Council / FDFA, “Uzbekistan: inauguration of the first maternity units modernised thanks to Karimova assets returned by Switzerland”, 24 Apr 2025, <a href="https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg" class="uri">https://www.news.admin.ch/en/newnsb/hHaFlQAiCpN-2hO6Wjfqg</a>.<a href="#fnref74" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn75"><p>U.S. Department of Justice, “U.S. Enters into Trilateral Agreement with Nigeria and Jersey to Repatriate Over $300 Million to Nigeria in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 3 Feb 2020, <a href="https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets" class="uri">https://www.justice.gov/archives/opa/pr/us-enters-trilateral-agreement-nigeria-and-jersey-repatriate-over-300-million-nigeria-assets</a>.<a href="#fnref75" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn76"><p>U.S. Department of Justice, “U.S. Repatriates over $311.7 Million in Assets to the Nigerian People that were Stolen by Former Nigerian Dictator and His Associates”, 4 May 2020, <a href="https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/us-repatriates-over-3117-million-assets-nigerian-people-were-stolen-former-nigerian-dictator</a>.<a href="#fnref76" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn77"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Repatriate Over $23 Million in Assets Stolen by Former Nigerian Dictator General Sani Abacha”, 23 Aug 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-repatriate-over-23-million-assets-stolen-former</a>.<a href="#fnref77" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn78"><p>U.S. Department of Justice, “United States Repatriates Over $20 Million in Assets Stolen by Former Nigerian Dictator”, 17 Nov 2022, <a href="https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator" class="uri">https://www.justice.gov/archives/opa/pr/united-states-repatriates-over-20-million-assets-stolen-former-nigerian-dictator</a>.<a href="#fnref78" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn79"><p>U.S. Department of Justice, “United States Enters into Agreement with Nigeria to Transfer $52.88M in Forfeited Corruption Proceeds for Uses to Benefit the Nigerian People”, 10 Jan 2025, <a href="https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses" class="uri">https://www.justice.gov/archives/opa/pr/united-states-enters-agreement-nigeria-transfer-5288m-forfeited-corruption-proceeds-uses</a>.<a href="#fnref79" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn80"><p>Government of Jersey, “Jersey confiscates £3.6 million proceeds of corruption” (Royal Court 24 Feb 2016; announcement 25 Feb 2016), <a href="https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx" class="uri">https://www.gov.je/News/2016/pages/jersey-confiscates-proceeds-of-corruption.aspx</a>.<a href="#fnref80" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn81"><p>Government of Jersey, “Chief Minister signs agreement with Kenya” (signed 3 Mar 2017; announcement 6 Mar 2017), <a href="https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx" class="uri">https://www.gov.je/News/2017/pages/kenyaassetsharing.aspx</a>.<a href="#fnref81" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn82"><p>Government of Jersey, “Confiscated funds to return to Kenya”, 12 Dec 2018, <a href="https://www.gov.je/news/2018/pages/kenyafunds.aspx" class="uri">https://www.gov.je/news/2018/pages/kenyafunds.aspx</a>.<a href="#fnref82" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn83"><p>Government of Jersey, “Jersey and Kenya sign historic Asset Recovery Agreement”, 28 Mar 2022, <a href="https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx" class="uri">https://www.gov.je/News/2022/pages/jerseykenyacovid-19.aspx</a>.<a href="#fnref83" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn84"><p>Government of Jersey, “Return of £829,500 to Republic of Mozambique confirmed”, 7 May 2024, <a href="https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx" class="uri">https://www.gov.je/News/2024/Pages/AssetReturnArrangementRepublicOfMozambique.aspx</a>.<a href="#fnref84" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn85"><p>U.S. Department of Justice, “Justice Department Repatriates Forfeited Funds to the Government of the Kyrgyz Republic”, 26 Feb 2019, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-forfeited-funds-government-kyrgyz-republic</a>.<a href="#fnref85" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>