<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Artem Radin">
<meta name="dcterms.date" content="2026-03-04">

<title>Asset Transfer Cases: Initial Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Asset_Transfer_Cases_Initial_Research_files/libs/clipboard/clipboard.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/popper.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/anchor.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/bootstrap/bootstrap-66f220744880a257c6c06aa45740e4a9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="mermaid-theme" content="neutral">
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="Asset_Transfer_Cases_Initial_Research_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="styles/summary.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose"><span class="header-section-number">1</span> Purpose</a></li>
  <li><a href="#interstate-case-matrix" id="toc-interstate-case-matrix" class="nav-link" data-scroll-target="#interstate-case-matrix"><span class="header-section-number">2</span> Interstate Case Matrix</a></li>
  <li><a href="#interstate-case-analysis-priority-cases" id="toc-interstate-case-analysis-priority-cases" class="nav-link" data-scroll-target="#interstate-case-analysis-priority-cases"><span class="header-section-number">3</span> Interstate Case Analysis (Priority Cases)</a></li>
  <li><a href="#additional-interstate-cases" id="toc-additional-interstate-cases" class="nav-link" data-scroll-target="#additional-interstate-cases"><span class="header-section-number">4</span> Additional Interstate Cases</a></li>
  <li><a href="#domestic-transfer-cases-comparator-models" id="toc-domestic-transfer-cases-comparator-models" class="nav-link" data-scroll-target="#domestic-transfer-cases-comparator-models"><span class="header-section-number">5</span> Domestic Transfer Cases (Comparator Models)</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Asset_Transfer_Cases_Initial_Research.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Asset Transfer Cases: Initial Research</h1>
<p class="subtitle lead">Verified Domestic and Cross-Border Transfers of Confiscated Criminal Assets</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Artem Radin </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Intern
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="purpose"><span class="header-section-number">1</span> Purpose</h2>
<p>This note analyzes <strong>interstate asset recovery and return mechanisms</strong> — the legal and institutional architecture by which one state returns confiscated criminal assets to another state or to a monitored public-benefit mechanism. It focuses on <strong>cross-border return cases</strong> where the transfer itself is documented, not merely freezing or seizure.</p>
<p>The paper provides <strong>case-by-case analysis</strong> of verified interstate returns, covering for each case: accusation, parties, procedural path, legal basis for confiscation and return, use of returned assets, and monitoring arrangements. Domestic victim-compensation models (Madoff, Western Union) are included briefly as <strong>comparator examples</strong> for distribution mechanics, but the primary focus is interstate restitution.</p>
<p>The note relies on <strong>official sources</strong>: press releases, treaties, MoUs, court decisions, and institutional monitoring reports. Source links appear under each case for independent verification.</p>
<p><strong>Pattern:</strong> In the strongest examples, interstate return requires (1) final confiscation/forfeiture in the recovering state; (2) a legal allocation mechanism (bilateral MoU, tripartite agreement, or repatriation decision); and (3) a monitored implementation vehicle. Returns are not simple budget transfers; they combine confiscation with use-of-funds controls and oversight.</p>
</section>
<section id="interstate-case-matrix" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="interstate-case-matrix"><span class="header-section-number">2</span> Interstate Case Matrix</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Case</th>
<th>Accusation / predicate offense</th>
<th>Parties</th>
<th>Forum / decision date</th>
<th>Amount</th>
<th>Legal basis for confiscation</th>
<th>Legal basis for return</th>
<th>Recipient / use of funds</th>
<th>Monitoring / joint project</th>
<th>Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Switzerland -&gt; Nigeria (Abacha II)</td>
<td>Corruption, embezzlement, laundering of state assets under Gen.&nbsp;Sani Abacha</td>
<td>Nigeria (requesting), Switzerland (confiscating), World Bank (monitoring)</td>
<td>Swiss Federal Supreme Court ATF 131 II 169 (7 Feb 2005); Geneva confiscation (8 Mar 2016); tripartite MOU (4 Dec 2017)</td>
<td>USD 321 million</td>
<td>Swiss criminal procedure (SCC Art. 69–72); Geneva prosecutor confiscation</td>
<td>Tripartite restitution agreement (Switzerland–Nigeria–World Bank); MLA framework (IRSG)</td>
<td>National Social Safety Net Project; cash transfers to poor households</td>
<td>World Bank monitors same as IDA Credit; Nigerian CSOs (NAR); bi-annual reports</td>
<td><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></td>
</tr>
<tr class="even">
<td>UK -&gt; Nigeria (Ibori)</td>
<td>Money laundering, conspiracy to defraud, forgery (Ibori network)</td>
<td>UK (confiscating), Nigeria (recipient)</td>
<td>UK confiscation orders since 2010; UK–Nigeria agreement (9 Mar 2021)</td>
<td>GBP 4.2 million</td>
<td>POCA 2002 s.6 confiscation orders</td>
<td>UK–Nigeria bilateral MoU and annex</td>
<td>Lagos–Ibadan Expressway, Abuja–Kano road, second Niger Bridge; NSIA administers</td>
<td>Cleen Foundation independent monitoring; Federal Monitoring Team; annual accountability reports</td>
<td><a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></td>
</tr>
<tr class="odd">
<td>U.S. -&gt; Malaysia (1MDB)</td>
<td>Misappropriation, bribery, money laundering (1MDB scheme)</td>
<td>U.S. (forfeiting), Malaysia (recipient)</td>
<td>U.S. civil forfeiture (41 actions from Jul 2016); Ninth Circuit (13 Jun 2023); DOJ repatriation tranches</td>
<td>~USD 1.4 billion</td>
<td>18 USC 981 civil forfeiture; Kleptocracy Asset Recovery Initiative</td>
<td>DOJ repatriation decision; bilateral U.S.–Malaysia framework</td>
<td>Malaysia 1MDB Asset Recovery Trust Account; benefit of people of Malaysia</td>
<td>Trust account administration; bilateral repatriation framework</td>
<td><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></td>
</tr>
<tr class="even">
<td>Switzerland -&gt; Kazakhstan</td>
<td>Money laundering (Geneva proceedings)</td>
<td>Switzerland, World Bank, Kazakhstan</td>
<td>Geneva confiscation (2011); Switzerland–World Bank agreement (Dec 2012)</td>
<td>USD 48 million (2012); USD 115 million (BOTA, 2007–2015)</td>
<td>Swiss criminal procedure; Geneva judicial authorities</td>
<td>Switzerland–World Bank agreement; BOTA Foundation (tripartite Switzerland–U.S.–Kazakhstan)</td>
<td>Youth policy, energy efficiency (2012); BOTA Child and Youth Development Foundation</td>
<td>World Bank; BOTA Foundation oversight</td>
<td><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a><a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></td>
</tr>
<tr class="odd">
<td>Switzerland / Luxembourg -&gt; Peru</td>
<td>Corruption (Montesinos/Fujimori-era; assets frozen since early 2000s)</td>
<td>Switzerland, Luxembourg, Peru</td>
<td>Confiscation procedures concluded 2020; trilateral agreement (16 Dec 2020)</td>
<td>USD 16.3 million (CHF) + EUR 9.7 million (LUX)</td>
<td>Swiss and Luxembourg criminal/forfeiture procedures; Peru non-conviction based forfeiture</td>
<td>Trilateral agreement (Switzerland–Luxembourg–Peru)</td>
<td>Rule of law, judicial transparency, anti-corruption projects</td>
<td>Peru judiciary, public ministry, justice ministry implementation; follow-up meeting May 2022</td>
<td><a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a><a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></td>
</tr>
</tbody>
</table>
</section>
<section id="interstate-case-analysis-priority-cases" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="interstate-case-analysis-priority-cases"><span class="header-section-number">3</span> Interstate Case Analysis (Priority Cases)</h2>
<section id="switzerland---nigeria-abacha-ii" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="switzerland---nigeria-abacha-ii"><span class="header-section-number">3.1</span> Switzerland -&gt; Nigeria (Abacha II)</h3>
<section id="essence-of-the-accusation" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="essence-of-the-accusation"><span class="header-section-number">3.1.1</span> Essence of the accusation</h4>
<p>Assets traced to late Gen.&nbsp;Sani Abacha and family held in Swiss banks — corruption, embezzlement, and laundering of illicit state assets. Nigeria requested mutual legal assistance for recovery.</p>
</section>
<section id="parties" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="parties"><span class="header-section-number">3.1.2</span> Parties</h4>
<ul>
<li><strong>Requesting state:</strong> Nigeria</li>
<li><strong>Confiscating state:</strong> Switzerland (Geneva prosecutorial authorities, Swiss Federal Supreme Court)</li>
<li><strong>Monitoring:</strong> World Bank; Nigerian civil society (Network on Asset Recovery)</li>
</ul>
</section>
<section id="procedural-path-and-court-decision" class="level4" data-number="3.1.3">
<h4 data-number="3.1.3" class="anchored" data-anchor-id="procedural-path-and-court-decision"><span class="header-section-number">3.1.3</span> Procedural path and court decision</h4>
<ol type="1">
<li>Nigeria submits MLA request under Swiss IRSG (Bundesgesetz über internationale Rechtshilfe in Strafsachen).</li>
<li>Swiss Federal Supreme Court ATF 131 II 169 (7 Feb 2005, case 1A.215/2004) confirms MLA and return parameters under IRSG while proceedings ongoing in Nigeria.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></li>
<li>Geneva prosecutor initiates criminal proceedings against Abba Abacha; assets frozen.</li>
<li>Swiss court (Dec 2014) rules repatriation conditional on World Bank monitoring.</li>
<li>Geneva Attorney General confiscates assets (8 Mar 2016); assets transferred to Swiss Confederation under SCC Art. 69–72.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></li>
<li>Tripartite MOU signed 4 Dec 2017 (Switzerland, Nigeria, World Bank) — USD 321 million.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></li>
</ol>
</section>
<section id="basis-for-return-of-assets" class="level4" data-number="3.1.4">
<h4 data-number="3.1.4" class="anchored" data-anchor-id="basis-for-return-of-assets"><span class="header-section-number">3.1.4</span> Basis for return of assets</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confiscation</strong></td>
<td>Swiss criminal procedure (SCC Art. 69–72); Geneva prosecutor confiscation order</td>
</tr>
<tr class="even">
<td><strong>Transfer abroad</strong></td>
<td>Tripartite restitution agreement; IRSG MLA framework</td>
</tr>
<tr class="odd">
<td><strong>Restrictions on use</strong></td>
<td>MOU requires World Bank monitoring, tranche-based disbursement, earmarking for National Social Safety Net Project</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects" class="level4" data-number="3.1.5">
<h4 data-number="3.1.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects"><span class="header-section-number">3.1.5</span> Use of returned assets / joint projects</h4>
<p>Funds applied to <strong>National Social Safety Net Project</strong> (IDA Credit P151488): targeted cash transfers to poor and vulnerable Nigerian households. Tranche-based release; same monitoring as IDA Credit. Nigerian CSOs under Network on Asset Recovery monitor cash-to-beneficiaries; bi-annual reports per tripartite agreement.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
</section>
<section id="verification-note" class="level4" data-number="3.1.6">
<h4 data-number="3.1.6" class="anchored" data-anchor-id="verification-note"><span class="header-section-number">3.1.6</span> Verification note</h4>
<ul>
<li>Transfer verified: Yes (official Swiss and World Bank sources)</li>
<li>Court decision verified: Yes (ATF 131 II 169)</li>
<li>Return instrument verified: Yes (2017 tripartite MOU)</li>
<li>Use-of-funds evidence verified: Yes (World Bank factsheet, project designation)</li>
<li>Open gaps: None material</li>
</ul>
</section>
<section id="sources" class="level4" data-number="3.1.7">
<h4 data-number="3.1.7" class="anchored" data-anchor-id="sources"><span class="header-section-number">3.1.7</span> Sources</h4>
<ul>
<li>Swiss Federal Supreme Court ATF 131 II 169<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></li>
<li>Swiss FDFA, Abacha letter of intent (8 Mar 2016)<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></li>
<li>Swiss FDFA, tripartite agreement (4 Dec 2017)<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></li>
<li>World Bank, monitoring of repatriated Abacha funds<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></li>
</ul>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        A1["Step 1: Nigeria submits MLA request to Switzerland&lt;br/&gt;for Abacha-linked assets held in Swiss banks"]
        A2["Step 2: Swiss authorities conduct IRSG admissibility review&lt;br/&gt;assess cooperation conditions under mutual legal assistance"]
        A3["Step 3: Swiss Federal Supreme Court ATF 131 II 169&lt;br/&gt;7 Feb 2005 — confirms legal parameters for cooperation and return"]
        A4["Step 4: Geneva prosecutor initiates criminal proceedings&lt;br/&gt;against Abba Abacha and related parties"]
        A5["Step 5: Swiss court Dec 2014: repatriation conditional on&lt;br/&gt;World Bank monitoring of use of funds"]
        A6["Step 6: Geneva Attorney General confiscates assets&lt;br/&gt;8 Mar 2016 — return process becomes legally possible"]
        A7["Step 7: Nigeria designates use: National Social Safety Net Project&lt;br/&gt;targeted cash transfers to poor and vulnerable Nigerians"]
        A8["Step 8: 4 Dec 2017: Tripartite MOU signed&lt;br/&gt;Switzerland, Nigeria, World Bank — USD 321 million"]
        A9["Step 9: Tranche-based disbursement to Nigeria&lt;br/&gt;funds applied to National Social Safety Net Project"]
        A10["Step 10: Cash transfers to beneficiaries&lt;br/&gt;poor and vulnerable Nigerians via IDA-financed project"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        M1["World Bank: monitors use of funds&lt;br/&gt;same manner as IDA Credit for National Social Safety Net Project"]
        M2["Nigerian CSOs under Network on Asset Recovery&lt;br/&gt;expertise in anti-corruption and asset recovery"]
        M3["CSOs monitor cash-to-beneficiaries&lt;br/&gt;bi-annual reports on use of funds"]
        M4["Transparency and accountability framework&lt;br/&gt;civil society oversight per tripartite agreement"]
    end

    A1 --&gt; A2 --&gt; A3 --&gt; A4 --&gt; A5 --&gt; A6 --&gt; A7 --&gt; A8 --&gt; A9 --&gt; A10
    A8 -.-&gt;|"enables"| M1
    A9 -.-&gt;|"subject to"| M2
    M2 --&gt; M3
    M1 --&gt; M4
    M3 --&gt; M4

    A1 -.-&gt; NA1
    A2 -.-&gt; NA2
    A3 -.-&gt; NA3
    A4 -.-&gt; NA4
    A5 -.-&gt; NA5
    A6 -.-&gt; NA6
    A7 -.-&gt; NA7
    A8 -.-&gt; NA8
    A9 -.-&gt; NA9
    A10 -.-&gt; NA10

    NA1["MLA request under Swiss IRSG Bundesgesetz über internationale Rechtshilfe in Strafsachen; assets traced to late Gen. Sani Abacha and family in Swiss banks; Nigeria as requesting state."]
    NA2["OFJ and cantonal authorities assessed admissibility under IRSG Art. 3; dual criminality and cooperation conditions reviewed."]
    NA3["ATF 131 II 169 7 Feb 2005 case 1A.215/2004; confirmed MLA and return parameters under IRSG while proceedings ongoing in Nigeria."]
    NA4["Procureur général de Genève initiated criminal proceedings against Abba Abacha; assets identified, frozen under Swiss criminal procedure."]
    NA5["Dec 2014 Swiss court ruling: repatriation conditional on World Bank monitoring of use; precondition for transfer."]
    NA6["8 Mar 2016 Procureur général Genève confiscation order; assets transferred to Swiss Confederation under Art. 69-72 SCC."]
    NA7["Nigeria designated National Social Safety Net Project P151488; IDA Credit; targeted cash transfers to poor households."]
    NA8["4 Dec 2017 tripartite MOU: Federal Govt Nigeria, Swiss Federal Council, World Bank; disbursement modalities and WB monitoring role."]
    NA9["Tranche-based release; funds applied to IDA-financed National Social Safety Net Project; same monitoring as IDA Credit."]
    NA10["Cash to beneficiaries; NAR CSOs monitor cash-to-beneficiaries; bi-annual reports per tripartite agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NA1,NA2,NA3,NA4,NA5,NA6,NA7,NA8,NA9,NA10 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="u.s.---malaysia-1mdb" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="u.s.---malaysia-1mdb"><span class="header-section-number">3.2</span> U.S. -&gt; Malaysia (1MDB)</h3>
<section id="essence-of-the-accusation-1" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="essence-of-the-accusation-1"><span class="header-section-number">3.2.1</span> Essence of the accusation</h4>
<p>Large-scale misappropriation, bribery, and money laundering linked to the 1MDB scheme. Assets traceable to the scheme were held or transited through the U.S. financial system.</p>
</section>
<section id="parties-1" class="level4" data-number="3.2.2">
<h4 data-number="3.2.2" class="anchored" data-anchor-id="parties-1"><span class="header-section-number">3.2.2</span> Parties</h4>
<ul>
<li><strong>Forfeiting state:</strong> United States (DOJ, Kleptocracy Asset Recovery Initiative)</li>
<li><strong>Recipient:</strong> Malaysia (1MDB Asset Recovery Trust Account)</li>
<li><strong>Beneficiary:</strong> People of Malaysia</li>
</ul>
</section>
<section id="procedural-path-and-court-decision-1" class="level4" data-number="3.2.3">
<h4 data-number="3.2.3" class="anchored" data-anchor-id="procedural-path-and-court-decision-1"><span class="header-section-number">3.2.3</span> Procedural path and court decision</h4>
<ol type="1">
<li>DOJ initiates 41 in rem civil forfeiture actions under 18 USC 981 from Jul 2016.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></li>
<li>U.S. district courts order restraint and seizure; res preserved pending litigation.</li>
<li>Ninth Circuit affirms seizure-preservation orders in <em>U.S. v. PetroSaudi Oil Services (Venezuela) Ltd.</em> (13 Jun 2023, Nos. 21-56228, 22-55025).<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></li>
<li>Settlements and default judgments; assets converted to recoverable value.</li>
<li>DOJ repatriation tranche decisions under bilateral U.S.–Malaysia framework.</li>
<li>Transfer to Malaysia 1MDB Asset Recovery Trust Account (e.g.&nbsp;USD 452m Aug 2021, USD 156m Jun 2024) — total ~USD 1.4 billion.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></li>
</ol>
</section>
<section id="basis-for-return-of-assets-1" class="level4" data-number="3.2.4">
<h4 data-number="3.2.4" class="anchored" data-anchor-id="basis-for-return-of-assets-1"><span class="header-section-number">3.2.4</span> Basis for return of assets</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confiscation</strong></td>
<td>18 USC 981 civil forfeiture; district court restraining orders and warrants of arrest in rem</td>
</tr>
<tr class="even">
<td><strong>Transfer abroad</strong></td>
<td>DOJ MLARS repatriation decision; bilateral U.S.–Malaysia repatriation framework</td>
</tr>
<tr class="odd">
<td><strong>Restrictions on use</strong></td>
<td>Designated trust account; use for public benefit per bilateral agreement</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-1" class="level4" data-number="3.2.5">
<h4 data-number="3.2.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-1"><span class="header-section-number">3.2.5</span> Use of returned assets / joint projects</h4>
<p>Funds administered via <strong>Malaysia 1MDB Asset Recovery Trust Account</strong> for the benefit of the people of Malaysia. Tranche-based returns; designated destination per bilateral framework. Trust account administration for public benefit.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a></p>
</section>
<section id="verification-note-1" class="level4" data-number="3.2.6">
<h4 data-number="3.2.6" class="anchored" data-anchor-id="verification-note-1"><span class="header-section-number">3.2.6</span> Verification note</h4>
<ul>
<li>Transfer verified: Yes (DOJ official releases)</li>
<li>Court decision verified: Yes (Ninth Circuit in PetroSaudi-related track)</li>
<li>Return instrument verified: Yes (bilateral repatriation framework; DOJ announcements)</li>
<li>Use-of-funds evidence verified: Partial (trust account designated; implementation details less public)</li>
<li>Open gaps: Trust account implementation and monitoring reports not as detailed as Swiss/UK cases</li>
</ul>
</section>
<section id="sources-1" class="level4" data-number="3.2.7">
<h4 data-number="3.2.7" class="anchored" data-anchor-id="sources-1"><span class="header-section-number">3.2.7</span> Sources</h4>
<ul>
<li>DOJ, 1MDB repatriation (13 Jun 2024)<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></li>
<li>U.S. Court of Appeals for the Ninth Circuit, <em>U.S. v. PetroSaudi Oil Services</em><a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></li>
</ul>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        B1["Step 1: DOJ initiates civil forfeiture actions&lt;br/&gt;from Jul 2016 — 41 actions targeting 1MDB-linked assets"]
        B2["Step 2: U.S. district courts order restraint and seizure&lt;br/&gt;preservation of res during litigation"]
        B3["Step 3: Ninth Circuit affirms seizure-preservation orders&lt;br/&gt;13 Jun 2023 — PetroSaudi-related track upheld"]
        B4["Step 4: Forfeiture pipeline: settlements and dispositions&lt;br/&gt;assets converted to recoverable value under U.S. law"]
        B5["Step 5: DOJ repatriation tranche decisions&lt;br/&gt;executive/legal-policy determination for Malaysia"]
        B6["Step 6: Transfer to Malaysia 1MDB Asset Recovery Trust Account&lt;br/&gt;e.g. USD 452m Aug 2021, USD 156m Jun 2024 — total ~USD 1.4bn"]
        B7["Step 7: Funds for benefit of people of Malaysia&lt;br/&gt;administered via Malaysian trust vehicle"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        N1["Malaysian 1MDB Asset Recovery Trust Account&lt;br/&gt;designated vehicle for repatriated proceeds"]
        N2["Trust account administration&lt;br/&gt;use for public benefit per agreement"]
        N3["Bilateral U.S.–Malaysia repatriation framework&lt;br/&gt;tranche-based returns with designated destination"]
    end

    B1 --&gt; B2 --&gt; B3 --&gt; B4 --&gt; B5 --&gt; B6 --&gt; B7
    B5 -.-&gt;|"governs"| N1
    B6 -.-&gt;|"to"| N1
    N1 --&gt; N2
    N2 --&gt; N3

    B1 -.-&gt; NB1
    B2 -.-&gt; NB2
    B3 -.-&gt; NB3
    B4 -.-&gt; NB4
    B5 -.-&gt; NB5
    B6 -.-&gt; NB6
    B7 -.-&gt; NB7

    NB1["41 in rem civil forfeiture actions under 18 USC 981 from Jul 2016; Kleptocracy Asset Recovery Initiative; assets traceable to 1MDB."]
    NB2["District court restraining orders and warrants of arrest in rem; 18 USC 981; res preserved pending forfeiture litigation."]
    NB3["9th Cir. U.S. v. PetroSaudi Oil Services Nos. 21-56228 22-55025 13 Jun 2023; affirmed interlocutory orders; USD 380m arbitration fund."]
    NB4["Settlements and default judgments under 18 USC 981; assets converted to recoverable value; DOJ disposition authority."]
    NB5["DOJ MLARS repatriation decision; assets legally forfeited; tranche determination under bilateral U.S.-Malaysia framework."]
    NB6["Wire to 1MDB Asset Recovery Trust Account; USD 452m Aug 2021, USD 156m Jun 2024; total ~USD 1.4bn per DOJ."]
    NB7["Trust account administered for benefit of people of Malaysia; designated recipient per bilateral repatriation agreement."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NB1,NB2,NB3,NB4,NB5,NB6,NB7 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="uk---nigeria-ibori" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="uk---nigeria-ibori"><span class="header-section-number">3.3</span> UK -&gt; Nigeria (Ibori)</h3>
<section id="essence-of-the-accusation-2" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="essence-of-the-accusation-2"><span class="header-section-number">3.3.1</span> Essence of the accusation</h4>
<p>Money laundering (POCA s.327), conspiracy to defraud, forgery — proceeds linked to former Delta State Governor James Ibori and associates. UK Met Police Proceeds of Crime Unit, NCA, and CPS investigated.</p>
</section>
<section id="parties-2" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="parties-2"><span class="header-section-number">3.3.2</span> Parties</h4>
<ul>
<li><strong>Confiscating state:</strong> United Kingdom (Met Police, NCA, CPS)</li>
<li><strong>Recipient:</strong> Nigeria (Federal Republic; Nigeria Sovereign Investment Authority administers)</li>
<li><strong>Monitoring:</strong> Cleen Foundation (independent); Federal Republic of Nigeria Monitoring Team</li>
</ul>
</section>
<section id="procedural-path-and-court-decision-2" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="procedural-path-and-court-decision-2"><span class="header-section-number">3.3.3</span> Procedural path and court decision</h4>
<ol type="1">
<li>UK investigation and prosecution of Ibori network.</li>
<li>Feb 2012: Ibori pleads guilty at Southwark Crown Court; 13 years imprisonment; confiscation proceedings under POCA s.6 followed.</li>
<li>UK confiscation orders since 2010 establish recoverable criminal property value.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a></li>
<li>UK–Nigeria return negotiations under 2016 MoU; framework for destination and safeguards.</li>
<li>9 Mar 2021: UK–Nigeria agreement and annex signed — GBP 4.2 million; project use and oversight conditions.<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a><a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a></li>
<li>Transfer under bilateral MoU; funds to NSIA for designated projects.</li>
</ol>
</section>
<section id="basis-for-return-of-assets-2" class="level4" data-number="3.3.4">
<h4 data-number="3.3.4" class="anchored" data-anchor-id="basis-for-return-of-assets-2"><span class="header-section-number">3.3.4</span> Basis for return of assets</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confiscation</strong></td>
<td>POCA 2002 s.6 confiscation orders</td>
</tr>
<tr class="even">
<td><strong>Transfer abroad</strong></td>
<td>UK–Nigeria bilateral MoU and annex (2021)</td>
</tr>
<tr class="odd">
<td><strong>Restrictions on use</strong></td>
<td>Annex: budget plan and work schedule per project; bar on disbursement to perpetrators and related persons; Cleen Foundation independent monitoring</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-joint-projects-2" class="level4" data-number="3.3.5">
<h4 data-number="3.3.5" class="anchored" data-anchor-id="use-of-returned-assets-joint-projects-2"><span class="header-section-number">3.3.5</span> Use of returned assets / joint projects</h4>
<p>Funds earmarked for <strong>Lagos–Ibadan Expressway, Abuja–Kano road, second Niger Bridge</strong> — infrastructure and public benefit. Nigeria Sovereign Investment Authority (NSIA) administers implementation. Cleen Foundation provides independent monitoring (infrastructure, anti-corruption, procurement). Federal Monitoring Team oversees implementation; annual accountability reports published.<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a></p>
</section>
<section id="verification-note-2" class="level4" data-number="3.3.6">
<h4 data-number="3.3.6" class="anchored" data-anchor-id="verification-note-2"><span class="header-section-number">3.3.6</span> Verification note</h4>
<ul>
<li>Transfer verified: Yes (UK official announcement and annex)</li>
<li>Court decision verified: Partial (annex confirms confiscation-order basis; full court order text not yet located)</li>
<li>Return instrument verified: Yes (2021 UK–Nigeria agreement and annex)</li>
<li>Use-of-funds evidence verified: Yes (project earmarking; monitoring structure)</li>
<li>Open gaps: Full-text public copy of Southwark confiscation orders pending</li>
</ul>
</section>
<section id="sources-2" class="level4" data-number="3.3.7">
<h4 data-number="3.3.7" class="anchored" data-anchor-id="sources-2"><span class="header-section-number">3.3.7</span> Sources</h4>
<ul>
<li>GOV.UK, UK–Nigeria return announcement (9 Mar 2021)<a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a></li>
<li>GOV.UK, annex on Ibori returned funds and confiscation orders<a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a></li>
</ul>
<div class="cell" data-fig-width="7" data-fig-height="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'flowchart': {'rankSpacing': 80, 'nodeSpacing': 60}}}%%
flowchart TD
    subgraph MAIN["Main transfer pathway"]
        C1["Step 1: UK investigation: Met Police, NCA, CPS&lt;br/&gt;Ibori network — money laundering, fraud, forgery"]
        C2["Step 2: Feb 2012: Ibori pleads guilty in UK court&lt;br/&gt;13 years imprisonment"]
        C3["Step 3: UK confiscation orders since 2010&lt;br/&gt;recoverable criminal property value established"]
        C4["Step 4: UK–Nigeria return negotiations&lt;br/&gt;framework for destination and safeguards"]
        C5["Step 5: 9 Mar 2021: UK–Nigeria agreement and annex signed&lt;br/&gt;GBP 4.2 million — project use and oversight conditions"]
        C6["Step 6: Transfer of GBP 4.2m to Nigeria&lt;br/&gt;under bilateral MoU"]
        C7["Step 7: Projects: Lagos–Ibadan Expressway, Abuja–Kano road&lt;br/&gt;second Niger Bridge — infrastructure and public benefit"]
        C8["Step 8: Nigeria Sovereign Investment Authority&lt;br/&gt;administers project implementation"]
    end

    subgraph MON["Monitoring &amp; oversight structure"]
        O1["Cleen Foundation: independent monitoring&lt;br/&gt;expertise in infrastructure, anti-corruption, procurement"]
        O2["Federal Republic of Nigeria Monitoring Team&lt;br/&gt;oversees implementation, regular progress reporting"]
        O3["Budget plan and work/expenditure schedule&lt;br/&gt;per project, agreed by UK and Nigerian representatives"]
        O4["Annual accountability reports&lt;br/&gt;published, information to Nigerian public"]
        O5["Bar on disbursement to perpetrators&lt;br/&gt;and related persons per annex"]
    end

    C1 --&gt; C2 --&gt; C3 --&gt; C4 --&gt; C5 --&gt; C6 --&gt; C7 --&gt; C8
    C5 -.-&gt;|"requires"| O1
    C6 -.-&gt;|"subject to"| O2
    O1 --&gt; O3
    O2 --&gt; O4
    O3 --&gt; O5
    O4 --&gt; O5

    C1 -.-&gt; NC1
    C2 -.-&gt; NC2
    C3 -.-&gt; NC3
    C4 -.-&gt; NC4
    C5 -.-&gt; NC5
    C6 -.-&gt; NC6
    C7 -.-&gt; NC7
    C8 -.-&gt; NC8

    NC1["Met Police Proceeds of Crime Unit, NCA, CPS; POCA 2002; money laundering s.327, conspiracy to defraud, forgery; Ibori network."]
    NC2["Southwark Crown Court Feb 2012; Ibori guilty plea; 13 years; confiscation proceedings under POCA s.6 followed."]
    NC3["Confiscation orders under POCA s.6 since 2010; recoverable amount and criminal property value; annex confirms order basis."]
    NC4["UK-Nigeria negotiations under 2016 MoU; return framework; destination, project earmarking, audit safeguards."]
    NC5["9 Mar 2021 UK-Nigeria agreement and annex; GBP 4.2m; budget plan and work schedule per project; bar on perpetrator disbursement."]
    NC6["Transfer under bilateral MoU; first return under 2016 framework; funds to NSIA for designated projects."]
    NC7["Earmarked: Lagos-Ibadan Expressway, Abuja-Kano road, second Niger Bridge; infrastructure and public benefit."]
    NC8["NSIA administers; Cleen Foundation independent monitoring; Federal Monitoring Team; annual accountability reports to public."]

    classDef noteBox fill:#fff8e1,stroke:#f9a825,stroke-width:2px,stroke-dasharray: 6 4
    class NC1,NC2,NC3,NC4,NC5,NC6,NC7,NC8 noteBox
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="additional-interstate-cases" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="additional-interstate-cases"><span class="header-section-number">4</span> Additional Interstate Cases</h2>
<section id="switzerland---kazakhstan" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="switzerland---kazakhstan"><span class="header-section-number">4.1</span> Switzerland -&gt; Kazakhstan</h3>
<section id="essence-of-the-accusation-3" class="level4" data-number="4.1.1">
<h4 data-number="4.1.1" class="anchored" data-anchor-id="essence-of-the-accusation-3"><span class="header-section-number">4.1.1</span> Essence of the accusation</h4>
<p>Money laundering; assets held in Swiss banks, confiscated in 2011 by Geneva judicial authorities in criminal proceedings.</p>
</section>
<section id="parties-3" class="level4" data-number="4.1.2">
<h4 data-number="4.1.2" class="anchored" data-anchor-id="parties-3"><span class="header-section-number">4.1.2</span> Parties</h4>
<ul>
<li><strong>Confiscating state:</strong> Switzerland (Geneva judicial authorities)</li>
<li><strong>Recipient:</strong> Kazakhstan</li>
<li><strong>Monitoring / vehicle:</strong> World Bank (2012 agreement); BOTA Foundation (2007–2015, tripartite Switzerland–U.S.–Kazakhstan)</li>
</ul>
</section>
<section id="procedural-path-and-decision" class="level4" data-number="4.1.3">
<h4 data-number="4.1.3" class="anchored" data-anchor-id="procedural-path-and-decision"><span class="header-section-number">4.1.3</span> Procedural path and decision</h4>
<ul>
<li>2011: Geneva authorities confiscate assets in money-laundering proceedings.</li>
<li>Dec 2012: Switzerland and World Bank sign agreement to return USD 48 million for youth policy and energy efficiency projects.<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a></li>
<li>Earlier track: BOTA Kazakh Child and Youth Development Foundation (2007) — USD 115 million returned by Dec 2015.<a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a></li>
</ul>
</section>
<section id="basis-for-return" class="level4" data-number="4.1.4">
<h4 data-number="4.1.4" class="anchored" data-anchor-id="basis-for-return"><span class="header-section-number">4.1.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confiscation</strong></td>
<td>Swiss criminal procedure; Geneva judicial authorities</td>
</tr>
<tr class="even">
<td><strong>Transfer abroad</strong></td>
<td>Switzerland–World Bank agreement (2012); BOTA tripartite framework (2007)</td>
</tr>
<tr class="odd">
<td><strong>Restrictions on use</strong></td>
<td>Project earmarking (youth, energy efficiency); BOTA Foundation oversight</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets" class="level4" data-number="4.1.5">
<h4 data-number="4.1.5" class="anchored" data-anchor-id="use-of-returned-assets"><span class="header-section-number">4.1.5</span> Use of returned assets</h4>
<p>2012 tranche: youth policy and energy efficiency projects. BOTA: Child and Youth Development Foundation.<a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a><a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a></p>
</section>
<section id="verification-note-3" class="level4" data-number="4.1.6">
<h4 data-number="4.1.6" class="anchored" data-anchor-id="verification-note-3"><span class="header-section-number">4.1.6</span> Verification note</h4>
<ul>
<li>Transfer verified: Yes (Swiss official sources)</li>
<li>Court decision verified: Partial (Geneva proceedings cited; full decision not linked)</li>
<li>Return instrument verified: Yes (2012 agreement; BOTA completion 2015)</li>
<li>Use-of-funds evidence verified: Yes (project designation; BOTA completion 2015)</li>
<li>Open gaps: Geneva court decision link</li>
</ul>
</section>
<section id="sources-3" class="level4" data-number="4.1.7">
<h4 data-number="4.1.7" class="anchored" data-anchor-id="sources-3"><span class="header-section-number">4.1.7</span> Sources</h4>
<ul>
<li>Swiss FDFA, Kazakhstan restitution (21 Dec 2012)<a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a></li>
<li>Swiss FDFA, BOTA completion (9 Dec 2015)<a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a></li>
</ul>
</section>
</section>
<section id="switzerland-luxembourg---peru" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="switzerland-luxembourg---peru"><span class="header-section-number">4.2</span> Switzerland / Luxembourg -&gt; Peru</h3>
<section id="essence-of-the-accusation-4" class="level4" data-number="4.2.1">
<h4 data-number="4.2.1" class="anchored" data-anchor-id="essence-of-the-accusation-4"><span class="header-section-number">4.2.1</span> Essence of the accusation</h4>
<p>Corruption linked to Vladimiro Montesinos Torres (head of Fujimori-era intelligence) and associates. Assets frozen in Swiss and Luxembourg banks since early 2000s. Peru used non-conviction based asset forfeiture.</p>
</section>
<section id="parties-4" class="level4" data-number="4.2.2">
<h4 data-number="4.2.2" class="anchored" data-anchor-id="parties-4"><span class="header-section-number">4.2.2</span> Parties</h4>
<ul>
<li><strong>Confiscating states:</strong> Switzerland, Luxembourg</li>
<li><strong>Recipient:</strong> Peru</li>
<li><strong>Use:</strong> Rule of law, judicial transparency, anti-corruption projects</li>
</ul>
</section>
<section id="procedural-path-and-decision-1" class="level4" data-number="4.2.3">
<h4 data-number="4.2.3" class="anchored" data-anchor-id="procedural-path-and-decision-1"><span class="header-section-number">4.2.3</span> Procedural path and decision</h4>
<ul>
<li>Assets frozen for nearly two decades; complex proceedings.</li>
<li>Confiscation procedures concluded 2020.</li>
<li>16 Dec 2020: Trilateral agreement signed — Switzerland USD 16.3 million, Luxembourg EUR 9.7 million.<a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a><a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a></li>
<li>Historic: first execution of a Peruvian confiscation order in a foreign jurisdiction based on Peru’s non-conviction based forfeiture.</li>
</ul>
</section>
<section id="basis-for-return-1" class="level4" data-number="4.2.4">
<h4 data-number="4.2.4" class="anchored" data-anchor-id="basis-for-return-1"><span class="header-section-number">4.2.4</span> Basis for return</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Element</th>
<th>Legal basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Confiscation</strong></td>
<td>Swiss and Luxembourg criminal/forfeiture procedures; Peru non-conviction based forfeiture</td>
</tr>
<tr class="even">
<td><strong>Transfer abroad</strong></td>
<td>Trilateral agreement (Switzerland–Luxembourg–Peru)</td>
</tr>
<tr class="odd">
<td><strong>Restrictions on use</strong></td>
<td>Earmarking for rule of law, judicial transparency, anti-corruption</td>
</tr>
</tbody>
</table>
</section>
<section id="use-of-returned-assets-1" class="level4" data-number="4.2.5">
<h4 data-number="4.2.5" class="anchored" data-anchor-id="use-of-returned-assets-1"><span class="header-section-number">4.2.5</span> Use of returned assets</h4>
<p>Projects strengthening rule of law, judicial transparency, and fight against corruption and impunity. Peru judiciary, public ministry, and justice ministry implement. Follow-up meeting May 2022 tracked implementation.<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a></p>
</section>
<section id="verification-note-4" class="level4" data-number="4.2.6">
<h4 data-number="4.2.6" class="anchored" data-anchor-id="verification-note-4"><span class="header-section-number">4.2.6</span> Verification note</h4>
<ul>
<li>Transfer verified: Yes (Swiss, Luxembourg, Peru official sources)</li>
<li>Court decision verified: Partial (confiscation procedures cited; court texts not linked)</li>
<li>Return instrument verified: Yes (2020 trilateral agreement)</li>
<li>Use-of-funds evidence verified: Yes (project designation; May 2022 follow-up)</li>
<li>Open gaps: Full court/confiscation decision links</li>
</ul>
</section>
<section id="sources-4" class="level4" data-number="4.2.7">
<h4 data-number="4.2.7" class="anchored" data-anchor-id="sources-4"><span class="header-section-number">4.2.7</span> Sources</h4>
<ul>
<li>Swiss FDFA, Peru trilateral agreement (16 Dec 2020)<a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a></li>
<li>Swiss FDFA, dynamic policy on restitution (16 Dec 2020)<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a></li>
</ul>
</section>
</section>
</section>
<section id="domestic-transfer-cases-comparator-models" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="domestic-transfer-cases-comparator-models"><span class="header-section-number">5</span> Domestic Transfer Cases (Comparator Models)</h2>
<p>Madoff and Western Union are <strong>domestic</strong> victim-compensation models — forfeited assets distributed to victims within the U.S. legal system. They illustrate <strong>distribution mechanics</strong> (remission, victim funds) but are <strong>not interstate restitution cases</strong>. Included here as comparators.</p>
<section id="u.s.-madoff-victim-fund" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="u.s.-madoff-victim-fund"><span class="header-section-number">5.1</span> U.S. Madoff Victim Fund</h3>
<p>DOJ-administered victim fund; <strong>&gt;USD 4.3 billion</strong> to <strong>40,930 victims in 127 countries</strong> (93.71% recovery).<a href="#fn44" class="footnote-ref" id="fnref44" role="doc-noteref"><sup>44</sup></a> Legal basis: civil and criminal forfeiture; formal DOJ victim compensation structure.</p>
</section>
<section id="u.s.-western-union-remission-fund" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="u.s.-western-union-remission-fund"><span class="header-section-number">5.2</span> U.S. Western Union Remission Fund</h3>
<p><strong>&gt;USD 420 million</strong> to <strong>&gt;175,000 victims</strong> via remission.<a href="#fn45" class="footnote-ref" id="fnref45" role="doc-noteref"><sup>45</sup></a> Funds forfeited from Western Union; formal remission process. Shows transfer-to-victims structure when proceeds pass through the state.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Swiss FDFA, “Trilateral agreement: Switzerland and Luxembourg to return illicitly acquired assets to Peru”, 16 Dec 2020, <a href="https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674" class="uri">https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674</a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Swiss Federal Supreme Court, ATF 131 II 169 (Abacha et consorts v. Office fédéral de la justice), case 1A.215/2004, 7 Feb 2005, <a href="https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document" class="uri">https://search.bger.ch/ext/eurospider/live/de/php/clir/http/index.php?highlight_docid=atf%3A%2F%2F131-II-169%3Ait&amp;lang=de&amp;type=show_document</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Swiss FDFA, “Switzerland and Nigeria conclude agreement on the return of USD 321 million of Abacha’s assets”, 8 Mar 2016, <a href="https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907" class="uri">https://www.eda.admin.ch/countries/romania/ro/home/aktuell/news.html/content/eda/en/meta/news/2016/3/8/60907</a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Swiss FDFA, “Restitution of USD 321 million by Switzerland to Nigeria under World Bank oversight: signing of a tripartite agreement”, 4 Dec 2017, <a href="https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088" class="uri">https://www.eda.admin.ch/countries/democratic-republic-congo/en/home/news/news.html/content/eda/en/meta/news/2017/12/4/69088</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>World Bank, “World Bank Monitoring of Repatriated Abacha Funds”, 4 Dec 2017, <a href="https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds" class="uri">https://www.worldbank.org/en/news/factsheet/2017/12/04/world-bank-monitoring-of-repatriated-abacha-funds</a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>U.S. Department of Justice, “Justice Department Repatriates $1.4B Misappropriated 1MDB Funds to Malaysia”, 13 Jun 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-repatriates-14b-misappropriated-1mdb-funds-malaysia</a>.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>U.S. Court of Appeals for the Ninth Circuit, <em>United States v. PetroSaudi Oil Services (Venezuela) Ltd.</em>, Nos. 21-56228 &amp; 22-55025, filed 13 Jun 2023, <a href="https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf" class="uri">https://cdn.ca9.uscourts.gov/datastore/opinions/2023/06/13/21-56228.pdf</a>.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p>GOV.UK, “UK to send millions of pounds recovered from corrupt officials back to Nigeria”, 9 Mar 2021, <a href="https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria" class="uri">https://www.gov.uk/government/news/uk-to-send-millions-of-pounds-recovered-from-corrupt-officials-back-to-nigeria</a>.<a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p>GOV.UK, “MoU between UK and Nigeria on the modalities for return of stolen assets confiscated by the UK: annex 1”, 2021, <a href="https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1" class="uri">https://www.gov.uk/government/publications/return-of-stolen-assets-confiscated-by-the-uk-agreement-between-the-uk-and-nigeria/mou-between-uk-and-nigeria-on-the-modalities-for-return-of-stolen-assets-confiscated-by-the-uk-annex-1</a>.<a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p>Swiss FDFA, “Switzerland and the World Bank sign agreement on the restitution of Kazakh assets”, 21 Dec 2012, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2012/12/21/47337</a>.<a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p>Swiss FDFA, “Restitution of stolen assets to Kazakhstan successfully completed”, 9 Dec 2015, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/news.html/content/eda/en/meta/news/2015/12/9/59867</a>.<a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p>Swiss FDFA, “Trilateral agreement: Switzerland and Luxembourg to return illicitly acquired assets to Peru”, 16 Dec 2020, <a href="https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674" class="uri">https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674</a>.<a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p>Swiss FDFA, “Trilateral agreement: Switzerland and Luxembourg to return illicitly acquired assets to Peru”, 16 Dec 2020, <a href="https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674" class="uri">https://www.eda.admin.ch/countries/new-zealand/en/home/news/news.html/content/eda/en/meta/news/2020/12/16/81674</a>.<a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p>Swiss FDFA, “A dynamic Swiss policy on restitution of illicit assets”, 16 Dec 2020, <a href="https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html" class="uri">https://www.eda.admin.ch/eda/en/fdfa/fdfa/aktuell/newsuebersicht/2020/12/abkommen-peru.html</a>.<a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn44"><p>U.S. Department of Justice, “Justice Department’s 10th Distribution Brings Total Provided to Over $4.3B in Nearly Full Recovery to Over 40,000 Victims in Madoff Ponzi Scheme”, 30 Dec 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery" class="uri">https://www.justice.gov/archives/opa/pr/justice-departments-10th-distribution-brings-total-provided-over-43b-nearly-full-recovery</a>.<a href="#fnref44" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn45"><p>U.S. Department of Justice, “Justice Department Begins Second Distribution of Forfeited Funds to Compensate Victims of Fraud Scheme Facilitated by Western Union”, 9 Sep 2024, <a href="https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud" class="uri">https://www.justice.gov/archives/opa/pr/justice-department-begins-second-distribution-forfeited-funds-compensate-victims-fraud</a>.<a href="#fnref45" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>